/**
 * DiscoverySettlementPolicy — the deterministic kernel policy that turns a
 * provisional discovery result into an authoritative one.
 *
 * Roadmap D4. Core principle:
 *
 *   LM proposes. Advisor assesses. Kernel settles. Certificate proves.
 *
 * Neither the discovery worker nor the readiness advisor can author the final
 * go / clarify / reject. Only a versioned policy may, and only against an
 * immutable SettlementInputSnapshot. The policy is PURE: no SQLite, no LM, no
 * workers, no I/O. It can be unit-tested in isolation.
 *
 * v1 is intentionally conservative and fully deterministic:
 *   - GO requires the worker AND the advisor to agree the Proposal is ready,
 *     grounded, and confident.
 *   - REJECT requires the worker AND the advisor to agree the Proposal should
 *     be rejected, with concrete blocking gaps.
 *   - Every indeterminate state fails-closed to CLARIFY.
 */

import { createHash } from 'node:crypto';

import type { DiscoverySettlementInputSnapshot } from './discovery-settlement-input.js';
import { canonicalJson } from '../shared/discovery-canonical.js';

/**
 * Version string for policy v1. Recorded in the snapshot, the settlement row,
 * and the outcome certificate. A policy version bump is a new idempotency
 * target (new settlement + new certificate); old certificates are preserved.
 */
export const DISCOVERY_SETTLEMENT_POLICY_VERSION = 'saga3.discovery-settlement-policy.v1';

/**
 * The stable, reason-bearing codes the policy emits alongside its decision.
 * These are NOT free text — they are a fixed enumeration so audit, dashboards,
 * and tests can branch on them deterministically. The rationale string is
 * assembled by the kernel from these codes, never generated by an LM.
 */
export type DiscoverySettlementReasonCode =
  // GO
  | 'GO_READY_AND_GROUNDED'
  // CLARIFY (fail-closed bucket)
  | 'CLARIFY_WORKER_REQUESTED'
  | 'CLARIFY_READINESS_MISSING'
  | 'CLARIFY_READINESS_FAILED'
  | 'CLARIFY_READINESS_PAUSED'
  | 'CLARIFY_READINESS_INCONCLUSIVE'
  | 'CLARIFY_CONDITIONALLY_READY'
  | 'CLARIFY_BLOCKING_GAPS'
  | 'CLARIFY_EVIDENCE_INSUFFICIENT'
  | 'CLARIFY_LOW_CONFIDENCE'
  | 'CLARIFY_WORKER_ADVISOR_CONFLICT'
  | 'CLARIFY_MANUAL_REVIEW_RECOMMENDED'
  | 'CLARIFY_REPEAT_DISCOVERY_RECOMMENDED'
  | 'CLARIFY_POLICY_FALLBACK'
  // REJECT
  | 'REJECT_WORKER_AND_ADVISOR_AGREE';

/**
 * The authoritative decision produced by the policy. `policy_version` and
 * `policy_hash` bind the decision to the exact policy that produced it.
 */
export interface DiscoverySettlementDecision {
  decision: 'go' | 'clarify' | 'reject';
  reason_codes: DiscoverySettlementReasonCode[];
  rationale: string;
  policy_version: string;
  policy_hash: string;
}

/**
 * One node of the deterministic policy evaluation trace (P0-4). Each node is a
 * predicate the policy considered, marked with WHICH branch it belongs to,
 * WHETHER it was actually evaluated, what ROLE it plays, WHETHER it contributed
 * to the final decision, and WHICH reason codes it emitted.
 *
 * Why a trace (not a flat "failed conditions" list): a generic superset of
 * predicates marked passed/failed lets a diagnosis cite an ALTERNATIVE-branch
 * predicate as the cause of the actual decision (e.g. citing
 * `worker_outcome_is_reject` as a CLARIFY cause when the worker recommended go).
 * The trace distinguishes:
 *
 *   - evaluation: 'passed' | 'failed' | 'not_evaluated'.
 *       * 'not_evaluated' covers short-circuited predicates (the policy returned
 *         before reaching them) and alternative-branch predicates (GO predicates
 *         under a REJECT decision, and vice versa). These MUST NOT be citable as
 *         causes — they did not participate in the decision.
 *   - role: 'supporting' | 'blocking' | 'fallback'.
 *       * 'supporting': a predicate that, when it holds, moves the policy toward
 *         this decision (GO conditions for a GO; REJECT conditions for a REJECT).
 *       * 'blocking': a predicate that, when it fails, moves the policy away
 *         from GO and toward CLARIFY (readiness missing/failed, blocking gaps,
 *         low confidence, evidence insufficient, worker/advisor conflict).
 *       * 'fallback': the catch-all CLARIFY_POLICY_FALLBACK.
 *   - contributed_to_decision: true iff THIS predicate actually contributed to
 *       the emitted decision + reason codes. For a GO, the passed GO conditions
 *       contribute (emitted GO_READY_AND_GROUNDED). For a REJECT, the passed
 *       REJECT conditions contribute (emitted REJECT_WORKER_AND_ADVISOR_AGREE).
 *       For a CLARIFY, the failed blocking conditions contribute, each emitting
 *       its reason code. Alternative-branch and not_evaluated predicates never
 *       contribute.
 *
 * D5's DiagnosisCase carries this trace; the diagnosis may cite ONLY nodes with
 * contributed_to_decision=true, and a cause's reason_codes must agree with the
 * cited node's emitted_reason_codes.
 */
export type SettlementConditionEvaluation = 'passed' | 'failed' | 'not_evaluated';
export type SettlementConditionRole = 'supporting' | 'blocking' | 'fallback';
export type SettlementConditionBranch = 'go' | 'reject' | 'clarify';

export interface SettlementConditionTrace {
  condition_id: string;
  branch: SettlementConditionBranch;
  evaluation: SettlementConditionEvaluation;
  role: SettlementConditionRole;
  contributed_to_decision: boolean;
  emitted_reason_codes: readonly DiscoverySettlementReasonCode[];
  source_refs: readonly string[];
}

/**
 * The full evaluation result: the authoritative decision PLUS the deterministic
 * trace. `settle()` returns `evaluate(input).decision`, so the observable
 * decision behaviour and the policy_hash are UNCHANGED (the manifest hashes the
 * decision rules, not the trace shape). D5 consumes the trace to build a
 * causally-correct DiagnosisCase.
 */
export interface SettlementEvaluation {
  decision: DiscoverySettlementDecision;
  trace: SettlementConditionTrace[];
}

/**
 * A versioned settlement policy. v1 is implemented by
 * `DiscoverySettlementPolicyV1`. The interface lets future versions coexist
 * with v1 (the snapshot records which version settled it).
 */
export interface DiscoverySettlementPolicy {
  readonly version: string;
  readonly contentHash: string;
  settle(input: DiscoverySettlementInputSnapshot): DiscoverySettlementDecision;
  /**
   * The deterministic evaluation trace (P0-4). Returns the SAME decision as
   * settle() PLUS the per-condition trace. settle() === evaluate(input).decision
   * by construction, so the policy identity (hash) and observable decision
   * behaviour are unchanged; the trace is additional read-only surface for D5.
   */
  evaluate(input: DiscoverySettlementInputSnapshot): SettlementEvaluation;
}

/**
 * Confidence thresholds for v1. A Proposal is only GO-able when the advisor's
 * confidence is at or above GO_MIN_CONFIDENCE, and only REJECT-able when at or
 * above REJECT_MIN_CONFIDENCE. Below the threshold the policy cannot commit in
 * either direction and falls back to CLARIFY.
 */
export const GO_MIN_CONFIDENCE = 0.70;
export const REJECT_MIN_CONFIDENCE = 0.70;

/**
 * The canonical POLICY MANIFEST — a full, declarative description of v1's
 * decision rules. The policy hash is SHA-256 over the canonical JSON of this
 * manifest, NOT merely over the version + thresholds. This is the "policy
 * identity" baked into every snapshot, settlement row, and certificate.
 *
 * Why a manifest and not just {version, thresholds}: the previous hash covered
 * only two numbers, so one could change a GO predicate (e.g. drop the evidence
 * requirement, flip clarify->go) while leaving version + thresholds — and the
 * certificate would carry the SAME policy_hash despite a different decision.
 * The manifest enumerates the actual GO/REJECT predicates, the evidence
 * requirement, the fallback decision, the thresholds, and the reason-code
 * mapping version, so ANY behavioural change changes the hash. (The manifest is
 * declarative; the imperative rules below must match it. A mismatch is caught
 * by the policy manifest unit tests, which assert the manifest equals the
 * actual rule behaviour.)
 */
export interface SettlementPolicyManifest {
  schema: 'saga3.discovery-settlement-policy-manifest.v1';
  version: string;
  go: {
    worker_outcome: 'go';
    proposal_evidence_min: number;
    readiness_overall: 'ready';
    blocking_gaps_max: number;
    evidence_grounding_status: 'sufficient';
    recommended_next_action: 'proceed_to_settlement';
    confidence_min: number;
  };
  reject: {
    worker_outcome: 'reject';
    readiness_overall: 'not_ready';
    recommended_next_action: 'reject';
    blocking_gaps_min: number;
    each_blocking_gap_must_have_source_refs: boolean;
    confidence_min: number;
  };
  fallback_decision: 'clarify';
  reason_code_mapping_version: number;
}

export const POLICY_V1_MANIFEST: SettlementPolicyManifest = {
  schema: 'saga3.discovery-settlement-policy-manifest.v1',
  version: DISCOVERY_SETTLEMENT_POLICY_VERSION,
  go: {
    worker_outcome: 'go',
    proposal_evidence_min: 1,
    readiness_overall: 'ready',
    blocking_gaps_max: 0,
    evidence_grounding_status: 'sufficient',
    recommended_next_action: 'proceed_to_settlement',
    confidence_min: GO_MIN_CONFIDENCE,
  },
  reject: {
    worker_outcome: 'reject',
    readiness_overall: 'not_ready',
    recommended_next_action: 'reject',
    blocking_gaps_min: 1,
    each_blocking_gap_must_have_source_refs: true,
    confidence_min: REJECT_MIN_CONFIDENCE,
  },
  fallback_decision: 'clarify',
  reason_code_mapping_version: 1,
};

/**
 * The stable content hash of policy v1: SHA-256 over the canonical JSON of the
 * full manifest (every GO/REJECT predicate, evidence requirement, thresholds,
 * fallback, reason-code mapping version). Changes to ANY observable rule change
 * this hash, which is exactly what we want: a new policy identity.
 */
export const POLICY_V1_CONTENT_HASH: string = createHash('sha256')
  .update(canonicalJson(POLICY_V1_MANIFEST))
  .digest('hex');

/**
 * Build the rationale string from reason codes. The kernel owns this — an LM
 * never generates settlement rationale. The text is deliberately mechanical so
 * that identical reason codes always produce identical rationale (the
 * certificate hash is reproducible).
 */
function rationaleFromCodes(codes: DiscoverySettlementReasonCode[]): string {
  if (codes.length === 0) return 'no reason codes';
  return codes.map(code => REASON_CODE_TEXT[code]).join('; ');
}

const REASON_CODE_TEXT: Record<DiscoverySettlementReasonCode, string> = {
  GO_READY_AND_GROUNDED: 'Proposal is ready, grounded, and confident enough to proceed',
  CLARIFY_WORKER_REQUESTED: 'Worker recommended clarification',
  CLARIFY_READINESS_MISSING: 'No accepted readiness assessment is available',
  CLARIFY_READINESS_FAILED: 'Readiness assessment failed',
  CLARIFY_READINESS_PAUSED: 'Readiness assessment was paused',
  CLARIFY_READINESS_INCONCLUSIVE: 'Readiness assessment was inconclusive',
  CLARIFY_CONDITIONALLY_READY: 'Readiness assessment was conditionally ready',
  CLARIFY_BLOCKING_GAPS: 'Blocking gaps remain',
  CLARIFY_EVIDENCE_INSUFFICIENT: 'Evidence grounding is insufficient',
  CLARIFY_LOW_CONFIDENCE: 'Confidence below the required threshold',
  CLARIFY_WORKER_ADVISOR_CONFLICT: 'Worker and advisor disagree',
  CLARIFY_MANUAL_REVIEW_RECOMMENDED: 'Advisor recommended manual review',
  CLARIFY_REPEAT_DISCOVERY_RECOMMENDED: 'Advisor recommended repeating discovery',
  CLARIFY_POLICY_FALLBACK: 'Indeterminate state; policy fell back to clarify',
  REJECT_WORKER_AND_ADVISOR_AGREE: 'Worker and advisor agree the Proposal should be rejected',
};

/**
 * Construct a CLARIFY decision with the given codes. Centralizes the fallback
 * shape so all non-GO/non-REJECT paths are uniform.
 */
function clarify(
  codes: DiscoverySettlementReasonCode[],
  version: string,
  policyHash: string,
): DiscoverySettlementDecision {
  const reason_codes: DiscoverySettlementReasonCode[] =
    codes.length > 0 ? codes : ['CLARIFY_POLICY_FALLBACK'];
  return {
    decision: 'clarify',
    reason_codes,
    rationale: rationaleFromCodes(reason_codes),
    policy_version: version,
    policy_hash: policyHash,
  };
}

/**
 * Settlement policy v1. Pure and deterministic. See module docstring for the
 * GO / REJECT / CLARIFY rules.
 */
export class DiscoverySettlementPolicyV1 implements DiscoverySettlementPolicy {
  readonly version = DISCOVERY_SETTLEMENT_POLICY_VERSION;
  readonly contentHash = POLICY_V1_CONTENT_HASH;

  /** settle() is exactly evaluate(input).decision — the trace is additive. */
  settle(input: DiscoverySettlementInputSnapshot): DiscoverySettlementDecision {
    return this.evaluate(input).decision;
  }

  /**
   * The deterministic evaluation. Builds the decision AND the per-condition
   * trace. The trace marks each predicate with its branch, whether it was
   * evaluated, its role, whether it contributed, and the reason codes it
   * emitted. Alternative-branch and short-circuited predicates are
   * 'not_evaluated' and never contribute — so a diagnosis cannot cite them as
   * causes of the actual decision.
   */
  evaluate(input: DiscoverySettlementInputSnapshot): SettlementEvaluation {
    const proposal = input.proposal.payload;
    const workerOutcome = proposal.recommended_outcome;
    const trace: SettlementConditionTrace[] = [];
    const v = this.version;
    const h = this.contentHash;

    // Helper to push a node.
    const node = (
      condition_id: string,
      branch: SettlementConditionBranch,
      evaluation: SettlementConditionEvaluation,
      role: SettlementConditionRole,
      contributed: boolean,
      codes: readonly DiscoverySettlementReasonCode[],
      source_refs: readonly string[],
    ): void => {
      trace.push({ condition_id, branch, evaluation, role, contributed_to_decision: contributed, emitted_reason_codes: codes, source_refs });
    };

    // ---- short-circuit 1: worker-requested clarify ------------------------
    if (workerOutcome === 'clarify') {
      node('worker_requested_clarify', 'clarify', 'passed', 'blocking', true,
        ['CLARIFY_WORKER_REQUESTED'], ['$.recommended_outcome']);
      return { decision: clarify(['CLARIFY_WORKER_REQUESTED'], v, h), trace };
    }

    // ---- short-circuit 2: no accepted readiness ---------------------------
    if (input.readiness.status !== 'accepted_by_kernel') {
      const code: DiscoverySettlementReasonCode =
        input.readiness.status === 'failed' ? 'CLARIFY_READINESS_FAILED'
        : input.readiness.status === 'paused' ? 'CLARIFY_READINESS_PAUSED'
        : 'CLARIFY_READINESS_MISSING';
      node('readiness_accepted', 'clarify', 'failed', 'blocking', true,
        [code], []);
      return { decision: clarify([code], v, h), trace };
    }

    // From here we have an accepted assessment (readiness.payload non-null by
    // snapshot construction, but guard).
    const assessment = input.readiness.payload;
    if (!assessment) {
      node('policy_fallback_malformed_snapshot', 'clarify', 'failed', 'fallback', true,
        ['CLARIFY_POLICY_FALLBACK'], []);
      return { decision: clarify(['CLARIFY_POLICY_FALLBACK'], v, h), trace };
    }

    const advisorOverall = assessment.overall_readiness;
    const advisorAction = assessment.recommended_next_action;
    const advisorConfidence = assessment.confidence;
    const blockingGaps = assessment.blocking_gaps;
    const evidenceDimension = assessment.dimension_assessments.evidence_grounding;

    // Evaluate the REJECT preconditions (supporting a reject decision).
    const rejectChecks = {
      workerReject: workerOutcome === 'reject',
      advisorNotReady: advisorOverall === 'not_ready',
      advisorActionReject: advisorAction === 'reject',
      blockingGapsPresent: blockingGaps.length > 0,
      eachBlockingGapGrounded: blockingGaps.length > 0
        && blockingGaps.every(g => Array.isArray(g.source_refs) && g.source_refs.length > 0),
      confidenceOk: advisorConfidence >= REJECT_MIN_CONFIDENCE,
    };

    // Evaluate the GO preconditions (supporting a go decision).
    const hasProposalEvidence = Array.isArray(proposal.evidence_refs)
      && proposal.evidence_refs.some(ref => typeof ref === 'string' && ref.trim().length > 0);
    const goChecks = {
      workerGo: workerOutcome === 'go',
      proposalEvidence: hasProposalEvidence,
      overallReady: advisorOverall === 'ready',
      noBlockingGaps: blockingGaps.length === 0,
      evidenceSufficient: evidenceDimension.status === 'sufficient',
      proceed: advisorAction === 'proceed_to_settlement',
      confidenceOk: advisorConfidence >= GO_MIN_CONFIDENCE,
    };

    // ---- REJECT path (§6.2) ----------------------------------------------
    if (workerOutcome === 'reject') {
      const allReject = rejectChecks.workerReject && rejectChecks.advisorNotReady
        && rejectChecks.advisorActionReject && rejectChecks.blockingGapsPresent
        && rejectChecks.eachBlockingGapGrounded && rejectChecks.confidenceOk;
      if (allReject) {
        // The reject decision is grounded in PASSED reject conditions. These
        // contribute; a REJECT diagnosis cites them (not failed GO conditions).
        for (const [id, held, refs] of [
          ['worker_outcome_is_reject', rejectChecks.workerReject, ['$.recommended_outcome']],
          ['overall_readiness_not_ready', rejectChecks.advisorNotReady, ['assessment.overall_readiness']],
          ['recommended_action_reject', rejectChecks.advisorActionReject, ['assessment.recommended_next_action']],
          ['blocking_gaps_present', rejectChecks.blockingGapsPresent, ['assessment.blocking_gaps']],
          ['each_blocking_gap_grounded', rejectChecks.eachBlockingGapGrounded, ['assessment.blocking_gaps']],
          ['confidence_above_reject_threshold', rejectChecks.confidenceOk, ['assessment.confidence']],
        ] as const) {
          node(id, 'reject', held ? 'passed' : 'failed', 'supporting', true,
            held ? ['REJECT_WORKER_AND_ADVISOR_AGREE'] : [], refs);
        }
        return {
          decision: {
            decision: 'reject', reason_codes: ['REJECT_WORKER_AND_ADVISOR_AGREE'],
            rationale: rationaleFromCodes(['REJECT_WORKER_AND_ADVISOR_AGREE']),
            policy_version: v, policy_hash: h,
          },
          trace,
        };
      }
      // Worker rejects but advisor does not coherently agree -> clarify. The
      // failed reject preconditions contribute, each emitting its clarify code.
      if (!rejectChecks.advisorNotReady && advisorOverall === 'inconclusive') {
        node('readiness_inconclusive', 'clarify', 'failed', 'blocking', true,
          ['CLARIFY_READINESS_INCONCLUSIVE'], ['assessment.overall_readiness']);
      }
      if (advisorAction === 'manual_review') {
        node('manual_review_recommended', 'clarify', 'failed', 'blocking', true,
          ['CLARIFY_MANUAL_REVIEW_RECOMMENDED'], ['assessment.recommended_next_action']);
      }
      if (advisorConfidence < REJECT_MIN_CONFIDENCE) {
        node('low_confidence', 'clarify', 'failed', 'blocking', true,
          ['CLARIFY_LOW_CONFIDENCE'], ['assessment.confidence']);
      }
      // Build the clarify codes (same logic as the original settle()).
      const codes: DiscoverySettlementReasonCode[] = [];
      if (advisorAction === 'manual_review') codes.push('CLARIFY_MANUAL_REVIEW_RECOMMENDED');
      if (advisorOverall === 'inconclusive') codes.push('CLARIFY_READINESS_INCONCLUSIVE');
      if (advisorConfidence < REJECT_MIN_CONFIDENCE) codes.push('CLARIFY_LOW_CONFIDENCE');
      if (codes.length === 0) {
        codes.push('CLARIFY_WORKER_ADVISOR_CONFLICT');
        node('worker_advisor_conflict', 'clarify', 'failed', 'blocking', true,
          ['CLARIFY_WORKER_ADVISOR_CONFLICT'], ['$.recommended_outcome', 'assessment.recommended_next_action']);
      }
      return { decision: clarify(codes, v, h), trace };
    }

    // ---- GO path (§6.1) ---------------------------------------------------
    if (workerOutcome === 'go') {
      const allGo = goChecks.proposalEvidence && goChecks.overallReady
        && goChecks.noBlockingGaps && goChecks.evidenceSufficient
        && goChecks.proceed && goChecks.confidenceOk;
      if (allGo) {
        // The go decision is grounded in PASSED GO conditions.
        for (const [id, refs] of [
          ['worker_outcome_is_go', ['$.recommended_outcome']],
          ['proposal_evidence_present', ['$.evidence_refs']],
          ['overall_readiness_ready', ['assessment.overall_readiness']],
          ['no_blocking_gaps', ['assessment.blocking_gaps']],
          ['evidence_grounding_sufficient', ['assessment.dimension_assessments.evidence_grounding']],
          ['recommended_action_proceed', ['assessment.recommended_next_action']],
          ['confidence_above_go_threshold', ['assessment.confidence']],
        ] as const) {
          node(id, 'go', 'passed', 'supporting', true, ['GO_READY_AND_GROUNDED'], refs);
        }
        return {
          decision: {
            decision: 'go', reason_codes: ['GO_READY_AND_GROUNDED'],
            rationale: rationaleFromCodes(['GO_READY_AND_GROUNDED']),
            policy_version: v, policy_hash: h,
          },
          trace,
        };
      }
      // Worker wants go but not all conditions hold -> clarify. Each failed
      // condition contributes and emits its reason code.
      if (!goChecks.proposalEvidence) {
        node('proposal_evidence_present', 'clarify', 'failed', 'blocking', true,
          ['CLARIFY_EVIDENCE_INSUFFICIENT'], ['$.evidence_refs']);
      }
      if (advisorOverall === 'conditionally_ready') {
        node('overall_readiness_ready', 'clarify', 'failed', 'blocking', true,
          ['CLARIFY_CONDITIONALLY_READY'], ['assessment.overall_readiness']);
      } else if (advisorOverall === 'inconclusive') {
        node('overall_readiness_ready', 'clarify', 'failed', 'blocking', true,
          ['CLARIFY_READINESS_INCONCLUSIVE'], ['assessment.overall_readiness']);
      }
      if (blockingGaps.length > 0) {
        node('no_blocking_gaps', 'clarify', 'failed', 'blocking', true,
          ['CLARIFY_BLOCKING_GAPS'], ['assessment.blocking_gaps']);
      }
      if (!goChecks.evidenceSufficient) {
        node('evidence_grounding_sufficient', 'clarify', 'failed', 'blocking', true,
          ['CLARIFY_EVIDENCE_INSUFFICIENT'], ['assessment.dimension_assessments.evidence_grounding']);
      }
      if (!goChecks.confidenceOk) {
        node('confidence_above_go_threshold', 'clarify', 'failed', 'blocking', true,
          ['CLARIFY_LOW_CONFIDENCE'], ['assessment.confidence']);
      }
      if (advisorAction === 'manual_review') {
        node('recommended_action_proceed', 'clarify', 'failed', 'blocking', true,
          ['CLARIFY_MANUAL_REVIEW_RECOMMENDED'], ['assessment.recommended_next_action']);
      } else if (advisorAction === 'repeat_discovery') {
        node('recommended_action_proceed', 'clarify', 'failed', 'blocking', true,
          ['CLARIFY_REPEAT_DISCOVERY_RECOMMENDED'], ['assessment.recommended_next_action']);
      }
      if (advisorOverall === 'not_ready' && advisorAction !== 'manual_review') {
        node('worker_advisor_agreement', 'clarify', 'failed', 'blocking', true,
          ['CLARIFY_WORKER_ADVISOR_CONFLICT'], ['$.recommended_outcome', 'assessment.overall_readiness']);
      }
      // Build the clarify codes (same logic as the original settle()).
      const codes: DiscoverySettlementReasonCode[] = [];
      if (!goChecks.proposalEvidence) codes.push('CLARIFY_EVIDENCE_INSUFFICIENT');
      if (advisorOverall === 'conditionally_ready') codes.push('CLARIFY_CONDITIONALLY_READY');
      else if (advisorOverall === 'inconclusive') codes.push('CLARIFY_READINESS_INCONCLUSIVE');
      if (blockingGaps.length > 0) codes.push('CLARIFY_BLOCKING_GAPS');
      if (!goChecks.evidenceSufficient) codes.push('CLARIFY_EVIDENCE_INSUFFICIENT');
      if (!goChecks.confidenceOk) codes.push('CLARIFY_LOW_CONFIDENCE');
      if (advisorAction === 'manual_review') codes.push('CLARIFY_MANUAL_REVIEW_RECOMMENDED');
      if (advisorAction === 'repeat_discovery') codes.push('CLARIFY_REPEAT_DISCOVERY_RECOMMENDED');
      if (advisorOverall === 'not_ready' && advisorAction !== 'manual_review') {
        codes.push('CLARIFY_WORKER_ADVISOR_CONFLICT');
      }
      if (codes.length === 0) {
        codes.push('CLARIFY_POLICY_FALLBACK');
        node('policy_fallback', 'clarify', 'failed', 'fallback', true,
          ['CLARIFY_POLICY_FALLBACK'], []);
      }
      return { decision: clarify(codes, v, h), trace };
    }

    // ---- catch-all: defer/inconclusive/failed worker outcome --------------
    node('policy_fallback_indeterminate_worker', 'clarify', 'failed', 'fallback', true,
      ['CLARIFY_POLICY_FALLBACK'], ['$.recommended_outcome']);
    return { decision: clarify(['CLARIFY_POLICY_FALLBACK'], v, h), trace };
  }
}

/**
 * The canonical single instance of policy v1. The settlement service uses this;
 * tests may construct their own to assert determinism.
 */
export const discoverySettlementPolicyV1 = new DiscoverySettlementPolicyV1();
