/**
 * DiscoverySettlementPolicy — the deterministic kernel policy that turns a
 * provisional discovery result into an authoritative one.
 *
 * Roadmap D4. Core principle:
 *
 *   LM proposes. Advisor assesses. Kernel settles. Certificate proves.
 *
 * Neither the discovery worker nor the readiness advisor can author the final
 * go / clarify / reject. Only a versioned policy may, and only against an
 * immutable SettlementInputSnapshot. The policy is PURE: no SQLite, no LM, no
 * workers, no I/O. It can be unit-tested in isolation.
 *
 * v1 is intentionally conservative and fully deterministic:
 *   - GO requires the worker AND the advisor to agree the Proposal is ready,
 *     grounded, and confident.
 *   - REJECT requires the worker AND the advisor to agree the Proposal should
 *     be rejected, with concrete blocking gaps.
 *   - Every indeterminate state fails-closed to CLARIFY.
 */

import { createHash } from 'node:crypto';

import type { DiscoverySettlementInputSnapshot } from './discovery-settlement-input.js';
import { canonicalJson } from '../shared/discovery-canonical.js';

/**
 * Version string for policy v1. Recorded in the snapshot, the settlement row,
 * and the outcome certificate. A policy version bump is a new idempotency
 * target (new settlement + new certificate); old certificates are preserved.
 */
export const DISCOVERY_SETTLEMENT_POLICY_VERSION = 'saga3.discovery-settlement-policy.v1';

/**
 * The stable, reason-bearing codes the policy emits alongside its decision.
 * These are NOT free text — they are a fixed enumeration so audit, dashboards,
 * and tests can branch on them deterministically. The rationale string is
 * assembled by the kernel from these codes, never generated by an LM.
 */
export type DiscoverySettlementReasonCode =
  // GO
  | 'GO_READY_AND_GROUNDED'
  // CLARIFY (fail-closed bucket)
  | 'CLARIFY_WORKER_REQUESTED'
  | 'CLARIFY_READINESS_MISSING'
  | 'CLARIFY_READINESS_FAILED'
  | 'CLARIFY_READINESS_PAUSED'
  | 'CLARIFY_READINESS_INCONCLUSIVE'
  | 'CLARIFY_CONDITIONALLY_READY'
  | 'CLARIFY_BLOCKING_GAPS'
  | 'CLARIFY_EVIDENCE_INSUFFICIENT'
  | 'CLARIFY_LOW_CONFIDENCE'
  | 'CLARIFY_WORKER_ADVISOR_CONFLICT'
  | 'CLARIFY_MANUAL_REVIEW_RECOMMENDED'
  | 'CLARIFY_REPEAT_DISCOVERY_RECOMMENDED'
  | 'CLARIFY_POLICY_FALLBACK'
  // REJECT
  | 'REJECT_WORKER_AND_ADVISOR_AGREE';

/**
 * The authoritative decision produced by the policy. `policy_version` and
 * `policy_hash` bind the decision to the exact policy that produced it.
 */
export interface DiscoverySettlementDecision {
  decision: 'go' | 'clarify' | 'reject';
  reason_codes: DiscoverySettlementReasonCode[];
  rationale: string;
  policy_version: string;
  policy_hash: string;
}

/**
 * A versioned settlement policy. v1 is implemented by
 * `DiscoverySettlementPolicyV1`. The interface lets future versions coexist
 * with v1 (the snapshot records which version settled it).
 */
export interface DiscoverySettlementPolicy {
  readonly version: string;
  readonly contentHash: string;
  settle(input: DiscoverySettlementInputSnapshot): DiscoverySettlementDecision;
}

/**
 * Confidence thresholds for v1. A Proposal is only GO-able when the advisor's
 * confidence is at or above GO_MIN_CONFIDENCE, and only REJECT-able when at or
 * above REJECT_MIN_CONFIDENCE. Below the threshold the policy cannot commit in
 * either direction and falls back to CLARIFY.
 */
export const GO_MIN_CONFIDENCE = 0.70;
export const REJECT_MIN_CONFIDENCE = 0.70;

/**
 * The canonical POLICY MANIFEST — a full, declarative description of v1's
 * decision rules. The policy hash is SHA-256 over the canonical JSON of this
 * manifest, NOT merely over the version + thresholds. This is the "policy
 * identity" baked into every snapshot, settlement row, and certificate.
 *
 * Why a manifest and not just {version, thresholds}: the previous hash covered
 * only two numbers, so one could change a GO predicate (e.g. drop the evidence
 * requirement, flip clarify->go) while leaving version + thresholds — and the
 * certificate would carry the SAME policy_hash despite a different decision.
 * The manifest enumerates the actual GO/REJECT predicates, the evidence
 * requirement, the fallback decision, the thresholds, and the reason-code
 * mapping version, so ANY behavioural change changes the hash. (The manifest is
 * declarative; the imperative rules below must match it. A mismatch is caught
 * by the policy manifest unit tests, which assert the manifest equals the
 * actual rule behaviour.)
 */
export interface SettlementPolicyManifest {
  schema: 'saga3.discovery-settlement-policy-manifest.v1';
  version: string;
  go: {
    worker_outcome: 'go';
    proposal_evidence_min: number;
    readiness_overall: 'ready';
    blocking_gaps_max: number;
    evidence_grounding_status: 'sufficient';
    recommended_next_action: 'proceed_to_settlement';
    confidence_min: number;
  };
  reject: {
    worker_outcome: 'reject';
    readiness_overall: 'not_ready';
    recommended_next_action: 'reject';
    blocking_gaps_min: number;
    each_blocking_gap_must_have_source_refs: boolean;
    confidence_min: number;
  };
  fallback_decision: 'clarify';
  reason_code_mapping_version: number;
}

export const POLICY_V1_MANIFEST: SettlementPolicyManifest = {
  schema: 'saga3.discovery-settlement-policy-manifest.v1',
  version: DISCOVERY_SETTLEMENT_POLICY_VERSION,
  go: {
    worker_outcome: 'go',
    proposal_evidence_min: 1,
    readiness_overall: 'ready',
    blocking_gaps_max: 0,
    evidence_grounding_status: 'sufficient',
    recommended_next_action: 'proceed_to_settlement',
    confidence_min: GO_MIN_CONFIDENCE,
  },
  reject: {
    worker_outcome: 'reject',
    readiness_overall: 'not_ready',
    recommended_next_action: 'reject',
    blocking_gaps_min: 1,
    each_blocking_gap_must_have_source_refs: true,
    confidence_min: REJECT_MIN_CONFIDENCE,
  },
  fallback_decision: 'clarify',
  reason_code_mapping_version: 1,
};

/**
 * The stable content hash of policy v1: SHA-256 over the canonical JSON of the
 * full manifest (every GO/REJECT predicate, evidence requirement, thresholds,
 * fallback, reason-code mapping version). Changes to ANY observable rule change
 * this hash, which is exactly what we want: a new policy identity.
 */
export const POLICY_V1_CONTENT_HASH: string = createHash('sha256')
  .update(canonicalJson(POLICY_V1_MANIFEST))
  .digest('hex');

/**
 * Build the rationale string from reason codes. The kernel owns this — an LM
 * never generates settlement rationale. The text is deliberately mechanical so
 * that identical reason codes always produce identical rationale (the
 * certificate hash is reproducible).
 */
function rationaleFromCodes(codes: DiscoverySettlementReasonCode[]): string {
  if (codes.length === 0) return 'no reason codes';
  return codes.map(code => REASON_CODE_TEXT[code]).join('; ');
}

const REASON_CODE_TEXT: Record<DiscoverySettlementReasonCode, string> = {
  GO_READY_AND_GROUNDED: 'Proposal is ready, grounded, and confident enough to proceed',
  CLARIFY_WORKER_REQUESTED: 'Worker recommended clarification',
  CLARIFY_READINESS_MISSING: 'No accepted readiness assessment is available',
  CLARIFY_READINESS_FAILED: 'Readiness assessment failed',
  CLARIFY_READINESS_PAUSED: 'Readiness assessment was paused',
  CLARIFY_READINESS_INCONCLUSIVE: 'Readiness assessment was inconclusive',
  CLARIFY_CONDITIONALLY_READY: 'Readiness assessment was conditionally ready',
  CLARIFY_BLOCKING_GAPS: 'Blocking gaps remain',
  CLARIFY_EVIDENCE_INSUFFICIENT: 'Evidence grounding is insufficient',
  CLARIFY_LOW_CONFIDENCE: 'Confidence below the required threshold',
  CLARIFY_WORKER_ADVISOR_CONFLICT: 'Worker and advisor disagree',
  CLARIFY_MANUAL_REVIEW_RECOMMENDED: 'Advisor recommended manual review',
  CLARIFY_REPEAT_DISCOVERY_RECOMMENDED: 'Advisor recommended repeating discovery',
  CLARIFY_POLICY_FALLBACK: 'Indeterminate state; policy fell back to clarify',
  REJECT_WORKER_AND_ADVISOR_AGREE: 'Worker and advisor agree the Proposal should be rejected',
};

/**
 * Construct a CLARIFY decision with the given codes. Centralizes the fallback
 * shape so all non-GO/non-REJECT paths are uniform.
 */
function clarify(
  codes: DiscoverySettlementReasonCode[],
  version: string,
  policyHash: string,
): DiscoverySettlementDecision {
  const reason_codes: DiscoverySettlementReasonCode[] =
    codes.length > 0 ? codes : ['CLARIFY_POLICY_FALLBACK'];
  return {
    decision: 'clarify',
    reason_codes,
    rationale: rationaleFromCodes(reason_codes),
    policy_version: version,
    policy_hash: policyHash,
  };
}

/**
 * Settlement policy v1. Pure and deterministic. See module docstring for the
 * GO / REJECT / CLARIFY rules.
 */
export class DiscoverySettlementPolicyV1 implements DiscoverySettlementPolicy {
  readonly version = DISCOVERY_SETTLEMENT_POLICY_VERSION;
  readonly contentHash = POLICY_V1_CONTENT_HASH;

  settle(input: DiscoverySettlementInputSnapshot): DiscoverySettlementDecision {
    const proposal = input.proposal.payload;
    const workerOutcome = proposal.recommended_outcome;

    // Worker-requested clarify short-circuits to clarify regardless of
    // readiness: the worker is the originator of the Proposal and its explicit
    // ask for clarification is respected.
    if (workerOutcome === 'clarify') {
      return clarify(['CLARIFY_WORKER_REQUESTED'], this.version, this.contentHash);
    }

    const readiness = input.readiness;

    // No accepted assessment -> the advisor is unavailable, errored, paused, or
    // never ran. Per the fail-closed mandate this is an authoritative CLARIFY
    // (not a pipeline failure — the pipeline still completes with a
    // certificate). The missing/failed/paused distinction is preserved in the
    // reason code AND in the semantic readiness-target idempotency key.
    if (readiness.status !== 'accepted_by_kernel') {
      const code =
        readiness.status === 'failed'
          ? 'CLARIFY_READINESS_FAILED'
          : readiness.status === 'paused'
            ? 'CLARIFY_READINESS_PAUSED'
            : 'CLARIFY_READINESS_MISSING';
      return clarify([code], this.version, this.contentHash);
    }

    // From here on we have an accepted assessment.
    const assessment = readiness.payload;
    // Guard against a malformed snapshot: an accepted_by_kernel status must
    // carry a payload. If it somehow does not, fail-closed.
    if (!assessment) {
      return clarify(['CLARIFY_POLICY_FALLBACK'], this.version, this.contentHash);
    }

    const advisorOverall = assessment.overall_readiness;
    const advisorAction = assessment.recommended_next_action;
    const advisorConfidence = assessment.confidence;
    const blockingGaps = assessment.blocking_gaps;
    const evidenceDimension = assessment.dimension_assessments.evidence_grounding;

    // ---- REJECT path (§6.2) ----------------------------------------------
    // Requires a coherent negative signal from BOTH worker and advisor.
    if (workerOutcome === 'reject') {
      const rejectConditions =
        advisorOverall === 'not_ready'
        && advisorAction === 'reject'
        && blockingGaps.length > 0
        && blockingGaps.every(g => Array.isArray(g.source_refs) && g.source_refs.length > 0)
        && advisorConfidence >= REJECT_MIN_CONFIDENCE;
      if (rejectConditions) {
        return {
          decision: 'reject',
          reason_codes: ['REJECT_WORKER_AND_ADVISOR_AGREE'],
          rationale: rationaleFromCodes(['REJECT_WORKER_AND_ADVISOR_AGREE']),
          policy_version: this.version,
          policy_hash: this.contentHash,
        };
      }
      // Worker rejects but the advisor does not coherently agree -> clarify.
      // Distinguish the common sub-cases for actionable reason codes.
      const codes: DiscoverySettlementReasonCode[] = [];
      if (advisorAction === 'manual_review') codes.push('CLARIFY_MANUAL_REVIEW_RECOMMENDED');
      if (advisorOverall === 'inconclusive') codes.push('CLARIFY_READINESS_INCONCLUSIVE');
      if (advisorConfidence < REJECT_MIN_CONFIDENCE) codes.push('CLARIFY_LOW_CONFIDENCE');
      if (codes.length === 0) codes.push('CLARIFY_WORKER_ADVISOR_CONFLICT');
      return clarify(codes, this.version, this.contentHash);
    }

    // ---- GO path (§6.1) ---------------------------------------------------
    // Only for worker go. Every condition must hold simultaneously.
    if (workerOutcome === 'go') {
      // The Proposal itself must carry at least one non-empty evidence_ref.
      // The advisor's evidence_grounding dimension alone is NOT enough: an
      // advisor can say 'sufficient' even when the Proposal's evidence_refs is
      // empty. The GO contract requires groundING in the Proposal, not just an
      // advisor opinion about it. (manifest.go.proposal_evidence_min = 1.)
      const hasProposalEvidence = Array.isArray(proposal.evidence_refs)
        && proposal.evidence_refs.some(ref => typeof ref === 'string' && ref.trim().length > 0);
      const goConditions = {
        proposalEvidence: hasProposalEvidence,
        overallReady: advisorOverall === 'ready',
        noBlockingGaps: blockingGaps.length === 0,
        evidenceSufficient:
          evidenceDimension.status === 'sufficient',
        proceed: advisorAction === 'proceed_to_settlement',
        confidenceOk: advisorConfidence >= GO_MIN_CONFIDENCE,
      };
      const allGo = Object.values(goConditions).every(Boolean);
      if (allGo) {
        return {
          decision: 'go',
          reason_codes: ['GO_READY_AND_GROUNDED'],
          rationale: rationaleFromCodes(['GO_READY_AND_GROUNDED']),
          policy_version: this.version,
          policy_hash: this.contentHash,
        };
      }
      // Worker wants go but not all conditions hold -> clarify with the
      // specific reasons that prevented a go.
      const codes: DiscoverySettlementReasonCode[] = [];
      if (!goConditions.proposalEvidence) codes.push('CLARIFY_EVIDENCE_INSUFFICIENT');
      if (advisorOverall === 'conditionally_ready') codes.push('CLARIFY_CONDITIONALLY_READY');
      else if (advisorOverall === 'inconclusive') codes.push('CLARIFY_READINESS_INCONCLUSIVE');
      if (blockingGaps.length > 0) codes.push('CLARIFY_BLOCKING_GAPS');
      if (!goConditions.evidenceSufficient) codes.push('CLARIFY_EVIDENCE_INSUFFICIENT');
      if (!goConditions.confidenceOk) codes.push('CLARIFY_LOW_CONFIDENCE');
      if (advisorAction === 'manual_review') codes.push('CLARIFY_MANUAL_REVIEW_RECOMMENDED');
      if (advisorAction === 'repeat_discovery') codes.push('CLARIFY_REPEAT_DISCOVERY_RECOMMENDED');
      // Worker go vs advisor not-ready/not-clarifying is a conflict.
      if (advisorOverall === 'not_ready' && advisorAction !== 'manual_review') {
        codes.push('CLARIFY_WORKER_ADVISOR_CONFLICT');
      }
      if (codes.length === 0) codes.push('CLARIFY_POLICY_FALLBACK');
      return clarify(codes, this.version, this.contentHash);
    }

    // ---- catch-all -------------------------------------------------------
    // Worker outcome is one of defer/inconclusive/failed (we already handled
    // go/clarify/reject). All of these are indeterminate -> clarify.
    return clarify(['CLARIFY_POLICY_FALLBACK'], this.version, this.contentHash);
  }
}

/**
 * The canonical single instance of policy v1. The settlement service uses this;
 * tests may construct their own to assert determinism.
 */
export const discoverySettlementPolicyV1 = new DiscoverySettlementPolicyV1();
