import type { ProcessModuleDefinition } from '../../domain/process-module.js';

export const FORMALIZATION_PROCESS_MODULE_REF = {
  name: 'solution-formalization',
  version: '1.0.0',
} as const;

const TRACKER = 'tool-templates/formalization/process-module-stage-tracker.md';
const ARTIFACT_CALL = 'tool-templates/formalization/artifact-create-call-template.json';
const TRACE_CALL = 'tool-templates/formalization/trace-add-call-template.json';
const DONE_CALL = 'tool-templates/formalization/worker-done-call-template.json';
const CHECKLIST = 'tool-templates/formalization/formalization-node-checklist.md';
const PROCESS_PROTOCOL_SKILL = 'saga-process-module-worker-protocol';

const COMMON_READ_TOOLS = [
  'task_get', 'artifact_list', 'trace_list', 'note_list', 'repository_checkout_list',
  'Read', 'Glob', 'Grep',
] as const;

const COMMON_WRITE_TOOLS = [
  ...COMMON_READ_TOOLS,
  'artifact_create', 'artifact_update', 'trace_add', 'worker_done', 'Write', 'Edit', 'Bash',
] as const;

export const formalizationProcessModule: ProcessModuleDefinition = {
  identity: {
    ...FORMALIZATION_PROCESS_MODULE_REF,
    kind: 'formalization',
    displayName: 'Solution Formalization',
    description: 'Converts an accepted discovery subject into a frozen, traceable and implementable solution contract.',
  },
  inputContract: { id: 'saga3.formalization-case.v1' },
  outputContract: { id: 'saga3.solution-contract-certificate.v1' },
  outcomes: [
    { code: 'accepted', description: 'A complete frozen solution contract is ready for downstream work.', terminal: true },
    { code: 'clarification-required', description: 'Required product or acceptance information is missing.', terminal: true },
    { code: 'inconsistent', description: 'The contract graph contains unresolved contradictions or traceability gaps.', terminal: true },
    { code: 'infeasible', description: 'The requested solution cannot be implemented under the accepted constraints.', terminal: true },
    { code: 'failed', description: 'Formalization infrastructure could not produce an authoritative result.', terminal: true },
  ],
  flow: {
    id: 'saga3.formalization.standard',
    version: '1.0.0',
    entryNodeId: 'define-product-contract',
    nodes: [
      {
        id: 'define-product-contract',
        label: 'Define Product Contract',
        kind: 'lm',
        description: 'Create PRD plus FR, NFR and RULE artifacts from the accepted discovery certificate.',
        executionProfile: 'formalization-product',
        outputSchema: { id: 'saga3.formalization-product-bundle.v1' },
      },
      {
        id: 'model-use-cases',
        label: 'Model Use Cases',
        kind: 'lm',
        description: 'Create use cases that cover the accepted functional requirements.',
        executionProfile: 'formalization-use-cases',
        outputSchema: { id: 'saga3.formalization-use-case-bundle.v1' },
      },
      {
        id: 'define-acceptance-contract',
        label: 'Define Acceptance Contract',
        kind: 'lm',
        description: 'Create acceptance criteria as contract data derived from UC, FR and NFR.',
        executionProfile: 'formalization-acceptance',
        outputSchema: { id: 'saga3.formalization-acceptance-bundle.v1' },
      },
      {
        id: 'reconcile-what',
        label: 'Reconcile WHAT Contract',
        kind: 'lm',
        description: 'Repair traceability, accept coherent WHAT artifacts and expose unresolved contradictions.',
        executionProfile: 'formalization-reconciler',
        outputSchema: { id: 'saga3.formalization-reconciliation-report.v1' },
      },
      {
        id: 'freeze-acceptance-baseline',
        label: 'Freeze Acceptance Baseline',
        kind: 'kernel',
        description: 'Compute and persist the immutable baseline hash from accepted acceptance criteria.',
        handler: 'formalization-baseline-freezer',
        inputSchema: { id: 'saga3.formalization-reconciliation-report.v1' },
        outputSchema: { id: 'saga3.acceptance-baseline-snapshot.v1' },
      },
      {
        id: 'define-architecture-contract',
        label: 'Define Architecture Contract',
        kind: 'lm',
        description: 'Create SRS, modules, invariants, ports and decomposition after the AC baseline is frozen.',
        executionProfile: 'formalization-architect',
        outputSchema: { id: 'saga3.formalization-architecture-bundle.v1' },
      },
      {
        id: 'settle-formalization',
        label: 'Settle Formalization',
        kind: 'kernel',
        description: 'Validate the complete contract graph and issue a solution contract certificate.',
        handler: 'formalization-settlement-policy',
        inputSchema: { id: 'saga3.formalization-settlement-input.v1' },
        outputSchema: { id: 'saga3.solution-contract-certificate.v1' },
      },
      ...[
        'accepted', 'clarification-required', 'inconsistent', 'infeasible', 'failed',
      ].map(code => ({
        id: `complete-${code}`,
        label: `Complete: ${code}`,
        kind: 'kernel' as const,
        description: `Emit the local Formalization process outcome '${code}'.`,
        handler: 'process-outcome-emitter',
        emitsOutcome: code,
      })),
    ],
    transitions: [
      { from: 'define-product-contract', to: 'model-use-cases', on: 'completed' },
      { from: 'define-product-contract', to: 'complete-clarification-required', on: 'clarification-required' },
      { from: 'define-product-contract', to: 'complete-failed', on: 'failed' },
      { from: 'model-use-cases', to: 'define-acceptance-contract', on: 'completed' },
      { from: 'model-use-cases', to: 'complete-clarification-required', on: 'clarification-required' },
      { from: 'model-use-cases', to: 'complete-failed', on: 'failed' },
      { from: 'define-acceptance-contract', to: 'reconcile-what', on: 'completed' },
      { from: 'define-acceptance-contract', to: 'complete-clarification-required', on: 'clarification-required' },
      { from: 'define-acceptance-contract', to: 'complete-failed', on: 'failed' },
      { from: 'reconcile-what', to: 'freeze-acceptance-baseline', on: 'reconciled' },
      { from: 'reconcile-what', to: 'complete-inconsistent', on: 'inconsistent' },
      { from: 'reconcile-what', to: 'complete-clarification-required', on: 'clarification-required' },
      { from: 'reconcile-what', to: 'complete-failed', on: 'failed' },
      { from: 'freeze-acceptance-baseline', to: 'define-architecture-contract', on: 'frozen' },
      { from: 'freeze-acceptance-baseline', to: 'complete-inconsistent', on: 'drift-detected' },
      { from: 'freeze-acceptance-baseline', to: 'complete-failed', on: 'failed' },
      { from: 'define-architecture-contract', to: 'settle-formalization', on: 'completed' },
      { from: 'define-architecture-contract', to: 'complete-infeasible', on: 'infeasible' },
      { from: 'define-architecture-contract', to: 'complete-clarification-required', on: 'clarification-required' },
      { from: 'define-architecture-contract', to: 'complete-failed', on: 'failed' },
      { from: 'settle-formalization', to: 'complete-accepted', on: 'accepted' },
      { from: 'settle-formalization', to: 'complete-clarification-required', on: 'clarification-required' },
      { from: 'settle-formalization', to: 'complete-inconsistent', on: 'inconsistent' },
      { from: 'settle-formalization', to: 'complete-infeasible', on: 'infeasible' },
      { from: 'settle-formalization', to: 'complete-failed', on: 'failed' },
    ],
    terminalNodeIds: [
      'complete-accepted',
      'complete-clarification-required',
      'complete-inconsistent',
      'complete-infeasible',
      'complete-failed',
    ],
  },
  artifacts: [
    { type: 'formalization-case', schema: { id: 'saga3.formalization-case.v1' }, authority: 'kernel', description: 'Input snapshot bound to the discovery certificate.' },
    { type: 'PRD', schema: { id: 'saga3.prd.v1' }, authority: 'worker', description: 'Product requirements document.' },
    { type: 'FR', schema: { id: 'saga3.functional-requirement.v1' }, authority: 'worker', description: 'Functional requirement.' },
    { type: 'NFR', schema: { id: 'saga3.non-functional-requirement.v1' }, authority: 'worker', description: 'Non-functional requirement.' },
    { type: 'RULE', schema: { id: 'saga3.business-rule.v1' }, authority: 'worker', description: 'Business rule with explicit enforcement trace.' },
    { type: 'UC', schema: { id: 'saga3.use-case.v1' }, authority: 'worker', description: 'Use case covering one or more FRs.' },
    { type: 'AC', schema: { id: 'saga3.acceptance-contract.v1' }, authority: 'worker', description: 'Acceptance criteria represented as contract data.' },
    { type: 'acceptance-baseline', schema: { id: 'saga3.acceptance-baseline-snapshot.v1' }, authority: 'kernel', description: 'Immutable accepted AC baseline.' },
    { type: 'SRS', schema: { id: 'saga3.srs.v1' }, authority: 'worker', description: 'Architecture and decomposition contract created after baseline freeze.' },
    { type: 'solution-contract-certificate', schema: { id: 'saga3.solution-contract-certificate.v1' }, authority: 'kernel', description: 'Authoritative result of the Formalization process.' },
  ],
  policies: [
    {
      id: 'formalization-what-reconciliation',
      version: '1.0.0',
      handler: 'formalization-what-reconciliation-policy',
      description: 'Requires complete WHAT-side traceability before baseline freeze.',
    },
    {
      id: 'formalization-settlement',
      version: '1.0.0',
      handler: 'formalization-settlement-policy',
      description: 'Validates the frozen acceptance and architecture graph before certification.',
    },
  ],
  invariants: [
    { id: 'formalization.what-before-how', description: 'PRD, FR, NFR, RULE, UC and AC are reconciled and frozen before SRS.', enforcement: 'runtime' },
    { id: 'formalization.trace-complete', description: 'Every accepted artifact has its required derived_from, covers or enforced_by links.', enforcement: 'policy' },
    { id: 'formalization.baseline-immutable', description: 'Accepted AC baseline cannot be edited in place.', enforcement: 'runtime' },
    { id: 'formalization.machine-fills-binding', description: 'Process, node, task, execution, artifact and schema identities are machine-filled.', enforcement: 'runtime' },
    { id: 'formalization.external-tracker', description: 'Every LM node maintains an external tracker and restart checkpoint.', enforcement: 'test' },
    { id: 'formalization.materialized-calls', description: 'Artifact, trace and completion MCP calls are materialized and checklist-verified.', enforcement: 'test' },
    { id: 'formalization.module-does-not-route', description: 'The module returns a local outcome and never starts Development directly.', enforcement: 'static' },
  ],
  executionProfiles: [
    {
      id: 'formalization-product',
      workIntentKind: 'formalization.product',
      workIntentSchema: { id: 'saga3.work-intent.formalization-product.v1' },
      taskKind: 'formalization.prd',
      executionSkill: 'saga-product',
      protocolSkill: PROCESS_PROTOCOL_SKILL,
      semanticSkill: 'saga-product',
      executionMode: 'artifact_change',
      allowedTools: COMMON_WRITE_TOOLS,
      trackerTemplate: TRACKER,
      workspaceTemplates: [ARTIFACT_CALL, TRACE_CALL, DONE_CALL],
      callTemplates: [ARTIFACT_CALL, TRACE_CALL, DONE_CALL],
      checklists: [CHECKLIST],
      outputSchema: { id: 'saga3.formalization-product-bundle.v1' },
      retryPolicy: { maxAttempts: 2, retryOn: ['schema-rejected', 'trace-gap'], backoff: 'none' },
      recoveryPolicy: { resumeFromCheckpoint: true, reuseWorkIntent: true, reuseAcceptedOutput: true, onExhausted: 'pause' },
    },
    {
      id: 'formalization-use-cases',
      workIntentKind: 'formalization.use-cases',
      workIntentSchema: { id: 'saga3.work-intent.formalization-use-cases.v1' },
      taskKind: 'formalization.uc',
      executionSkill: 'saga-analyst',
      protocolSkill: PROCESS_PROTOCOL_SKILL,
      semanticSkill: 'saga-analyst',
      executionMode: 'artifact_change',
      allowedTools: COMMON_WRITE_TOOLS,
      trackerTemplate: TRACKER,
      workspaceTemplates: [ARTIFACT_CALL, TRACE_CALL, DONE_CALL],
      callTemplates: [ARTIFACT_CALL, TRACE_CALL, DONE_CALL],
      checklists: [CHECKLIST],
      outputSchema: { id: 'saga3.formalization-use-case-bundle.v1' },
      retryPolicy: { maxAttempts: 2, retryOn: ['schema-rejected', 'trace-gap'], backoff: 'none' },
      recoveryPolicy: { resumeFromCheckpoint: true, reuseWorkIntent: true, reuseAcceptedOutput: true, onExhausted: 'pause' },
    },
    {
      id: 'formalization-acceptance',
      workIntentKind: 'formalization.acceptance',
      workIntentSchema: { id: 'saga3.work-intent.formalization-acceptance.v1' },
      taskKind: 'formalization.ac',
      executionSkill: 'saga-analyst',
      protocolSkill: PROCESS_PROTOCOL_SKILL,
      semanticSkill: 'saga-analyst',
      executionMode: 'artifact_change',
      allowedTools: COMMON_WRITE_TOOLS,
      trackerTemplate: TRACKER,
      workspaceTemplates: [ARTIFACT_CALL, TRACE_CALL, DONE_CALL],
      callTemplates: [ARTIFACT_CALL, TRACE_CALL, DONE_CALL],
      checklists: [CHECKLIST],
      outputSchema: { id: 'saga3.formalization-acceptance-bundle.v1' },
      retryPolicy: { maxAttempts: 2, retryOn: ['schema-rejected', 'trace-gap'], backoff: 'none' },
      recoveryPolicy: { resumeFromCheckpoint: true, reuseWorkIntent: true, reuseAcceptedOutput: true, onExhausted: 'pause' },
    },
    {
      id: 'formalization-reconciler',
      workIntentKind: 'formalization.reconcile',
      workIntentSchema: { id: 'saga3.work-intent.formalization-reconciliation.v1' },
      taskKind: 'formalization.reconciliation',
      executionSkill: 'saga-reconciler',
      protocolSkill: PROCESS_PROTOCOL_SKILL,
      semanticSkill: 'saga-reconciler',
      executionMode: 'artifact_change',
      allowedTools: COMMON_WRITE_TOOLS,
      trackerTemplate: TRACKER,
      workspaceTemplates: [TRACE_CALL, DONE_CALL],
      callTemplates: [TRACE_CALL, DONE_CALL],
      checklists: [CHECKLIST],
      outputSchema: { id: 'saga3.formalization-reconciliation-report.v1' },
      retryPolicy: { maxAttempts: 2, retryOn: ['trace-gap', 'baseline-race'], backoff: 'fixed' },
      recoveryPolicy: { resumeFromCheckpoint: true, reuseWorkIntent: true, reuseAcceptedOutput: true, onExhausted: 'escalate' },
    },
    {
      id: 'formalization-architect',
      workIntentKind: 'formalization.architecture',
      workIntentSchema: { id: 'saga3.work-intent.formalization-architecture.v1' },
      taskKind: 'formalization.srs',
      executionSkill: 'saga-architect',
      protocolSkill: PROCESS_PROTOCOL_SKILL,
      semanticSkill: 'saga-architect',
      executionMode: 'artifact_change',
      allowedTools: COMMON_WRITE_TOOLS,
      trackerTemplate: TRACKER,
      workspaceTemplates: [ARTIFACT_CALL, TRACE_CALL, DONE_CALL],
      callTemplates: [ARTIFACT_CALL, TRACE_CALL, DONE_CALL],
      checklists: [CHECKLIST],
      outputSchema: { id: 'saga3.formalization-architecture-bundle.v1' },
      retryPolicy: { maxAttempts: 2, retryOn: ['schema-rejected', 'trace-gap', 'invariant-gap'], backoff: 'none' },
      recoveryPolicy: { resumeFromCheckpoint: true, reuseWorkIntent: true, reuseAcceptedOutput: true, onExhausted: 'escalate' },
    },
  ],
};
