import type { ProcessModuleDefinition } from '../../domain/process-module.js';

export const FORMALIZATION_PROCESS_MODULE_REF = {
  name: 'solution-formalization',
  version: '1.0.0',
} as const;

const TRACKER = 'tool-templates/formalization/process-module-stage-tracker.md';
const ARTIFACT_CALL = 'tool-templates/formalization/artifact-create-call-template.json';
const TRACE_CALL = 'tool-templates/formalization/trace-add-call-template.json';
const DONE_CALL = 'tool-templates/formalization/worker-done-call-template.json';
const CHECKLIST = 'tool-templates/formalization/formalization-node-checklist.md';
const PROCESS_PROTOCOL_SKILL = 'saga-process-module-worker-protocol';

const COMMON_READ_TOOLS = [
  'task_get', 'artifact_list', 'trace_list', 'note_list', 'repository_checkout_list',
  'Read', 'Glob', 'Grep',
] as const;

const COMMON_WRITE_TOOLS = [
  ...COMMON_READ_TOOLS,
  'artifact_create', 'artifact_update', 'trace_add', 'worker_done', 'Write', 'Edit', 'Bash',
] as const;

export const formalizationProcessModule: ProcessModuleDefinition = {
  identity: {
    ...FORMALIZATION_PROCESS_MODULE_REF,
    kind: 'formalization',
    displayName: 'Solution Formalization',
    description: 'Converts an accepted discovery subject into a frozen, traceable and implementable solution contract.',
  },
  inputContract: { id: 'saga3.formalization-case.v1' },
  outputContract: { id: 'saga3.solution-contract-certificate.v1' },
  outcomes: [
    { code: 'formalized', description: 'A complete frozen solution contract is ready for downstream work.', terminal: true },
    { code: 'clarification-required', description: 'Required product or acceptance information is missing.', terminal: true },
    { code: 'inconsistent', description: 'The contract graph contains unresolved contradictions or traceability gaps.', terminal: true },
    { code: 'infeasible', description: 'The requested solution cannot be implemented under the accepted constraints.', terminal: true },
    { code: 'failed', description: 'Formalization infrastructure could not produce an authoritative result.', terminal: true },
  ],
  flow: {
    id: 'saga3.formalization.standard',
    version: '1.0.0',
    entryNodeId: 'define-product-contract',
    nodes: [
      {
        id: 'define-product-contract',
        label: 'Define Product Contract',
        kind: 'lm',
        description: 'Create PRD plus FR, NFR and RULE artifacts from the accepted discovery certificate.',
        executionProfile: 'formalization-product',
        outputSchema: { id: 'saga3.formalization-product-bundle.v1' },
      },
      {
        id: 'resolve-product-contract',
        label: 'Resolve Product Contract',
        kind: 'kernel',
        description: 'Resolve the exact canonical PRD/FR/NFR/RULE writes made by the fenced LM execution.',
        handler: 'formalization-resolve-product-contract',
        outputSchema: { id: 'saga3.formalization-product-bundle.v1' },
      },
      {
        id: 'model-use-cases',
        label: 'Model Use Cases',
        kind: 'lm',
        description: 'Create use cases that cover the accepted functional requirements.',
        executionProfile: 'formalization-use-cases',
        outputSchema: { id: 'saga3.formalization-use-case-bundle.v1' },
      },
      {
        id: 'resolve-use-cases',
        label: 'Resolve Use Cases',
        kind: 'kernel',
        description: 'Resolve the exact canonical UC writes and their traces from the fenced LM execution.',
        handler: 'formalization-resolve-use-cases',
        outputSchema: { id: 'saga3.formalization-use-case-bundle.v1' },
      },
      {
        id: 'define-acceptance-contract',
        label: 'Define Acceptance Contract',
        kind: 'lm',
        description: 'Create acceptance criteria as contract data derived from UC, FR and NFR.',
        executionProfile: 'formalization-acceptance',
        outputSchema: { id: 'saga3.formalization-acceptance-bundle.v1' },
      },
      {
        id: 'resolve-acceptance-contract',
        label: 'Resolve Acceptance Contract',
        kind: 'kernel',
        description: 'Resolve the exact canonical AC writes and their traces from the fenced LM execution.',
        handler: 'formalization-resolve-acceptance-contract',
        outputSchema: { id: 'saga3.formalization-acceptance-bundle.v1' },
      },
      {
        id: 'reconcile-what',
        label: 'Reconcile WHAT Contract',
        kind: 'lm',
        description: 'Repair permitted traceability gaps and expose unresolved WHAT-side contradictions.',
        executionProfile: 'formalization-reconciler',
        outputSchema: { id: 'saga3.formalization-reconciliation-report.v1' },
      },
      {
        id: 'resolve-reconciliation',
        label: 'Resolve WHAT Reconciliation',
        kind: 'kernel',
        description: 'Re-read the exact WHAT lineage, validate acceptance and traceability, and materialize the reconciliation result.',
        handler: 'formalization-resolve-reconciliation',
        outputSchema: { id: 'saga3.formalization-reconciliation-report.v1' },
      },
      {
        id: 'freeze-acceptance-baseline',
        label: 'Freeze Acceptance Baseline',
        kind: 'kernel',
        description: 'Compute and persist the immutable baseline hash from accepted acceptance criteria.',
        handler: 'formalization-baseline-freezer',
        inputSchema: { id: 'saga3.formalization-reconciliation-report.v1' },
        outputSchema: { id: 'saga3.acceptance-baseline-snapshot.v1' },
      },
      {
        id: 'define-architecture-contract',
        label: 'Define Architecture Contract',
        kind: 'lm',
        description: 'Create SRS, modules, invariants, ports and decomposition after the AC baseline is frozen.',
        executionProfile: 'formalization-architect',
        outputSchema: { id: 'saga3.formalization-architecture-bundle.v1' },
      },
      {
        id: 'resolve-architecture-contract',
        label: 'Resolve Architecture Contract',
        kind: 'kernel',
        description: 'Resolve the exact canonical SRS write and verify it against the frozen acceptance baseline.',
        handler: 'formalization-resolve-architecture-contract',
        outputSchema: { id: 'saga3.formalization-architecture-bundle.v1' },
      },
      {
        id: 'settle-formalization',
        label: 'Settle Formalization',
        kind: 'kernel',
        description: 'Validate the complete contract graph and issue a solution contract certificate.',
        handler: 'formalization-settlement-policy',
        inputSchema: { id: 'saga3.formalization-settlement-input.v1' },
        outputSchema: { id: 'saga3.solution-contract-certificate.v1' },
      },
      ...[
        'formalized', 'clarification-required', 'inconsistent', 'infeasible', 'failed',
      ].map(code => ({
        id: `complete-${code}`,
        label: `Complete: ${code}`,
        kind: 'kernel' as const,
        description: `Emit the local Formalization process outcome '${code}'.`,
        handler: 'process-outcome-emitter',
        emitsOutcome: code,
      })),
    ],
    transitions: [
      // LM nodes emit only physical runtime events. Even runtime.failed reaches
      // the resolver because the worker may have committed durable MCP writes
      // before its process died. The resolver decides whether a domain product
      // exists by reading the exact managed-execution provenance ledger.
      { from: 'define-product-contract', to: 'resolve-product-contract', on: 'runtime.completed' },
      { from: 'define-product-contract', to: 'resolve-product-contract', on: 'runtime.failed' },
      { from: 'resolve-product-contract', to: 'model-use-cases', on: 'domain.completed' },
      { from: 'resolve-product-contract', to: 'define-product-contract', on: 'domain.repair-required' },
      { from: 'resolve-product-contract', to: 'define-product-contract', on: 'domain.acceptance-blocked' },
      { from: 'resolve-product-contract', to: 'complete-clarification-required', on: 'domain.clarification-required' },
      { from: 'resolve-product-contract', to: 'complete-failed', on: 'domain.failed' },

      { from: 'model-use-cases', to: 'resolve-use-cases', on: 'runtime.completed' },
      { from: 'model-use-cases', to: 'resolve-use-cases', on: 'runtime.failed' },
      { from: 'resolve-use-cases', to: 'define-acceptance-contract', on: 'domain.completed' },
      { from: 'resolve-use-cases', to: 'model-use-cases', on: 'domain.repair-required' },
      { from: 'resolve-use-cases', to: 'model-use-cases', on: 'domain.acceptance-blocked' },
      { from: 'resolve-use-cases', to: 'complete-clarification-required', on: 'domain.clarification-required' },
      { from: 'resolve-use-cases', to: 'complete-inconsistent', on: 'domain.inconsistent' },
      { from: 'resolve-use-cases', to: 'complete-failed', on: 'domain.failed' },

      { from: 'define-acceptance-contract', to: 'resolve-acceptance-contract', on: 'runtime.completed' },
      { from: 'define-acceptance-contract', to: 'resolve-acceptance-contract', on: 'runtime.failed' },
      { from: 'resolve-acceptance-contract', to: 'reconcile-what', on: 'domain.completed' },
      { from: 'resolve-acceptance-contract', to: 'define-acceptance-contract', on: 'domain.repair-required' },
      { from: 'resolve-acceptance-contract', to: 'define-acceptance-contract', on: 'domain.acceptance-blocked' },
      { from: 'resolve-acceptance-contract', to: 'complete-clarification-required', on: 'domain.clarification-required' },
      { from: 'resolve-acceptance-contract', to: 'complete-inconsistent', on: 'domain.inconsistent' },
      { from: 'resolve-acceptance-contract', to: 'complete-failed', on: 'domain.failed' },

      { from: 'reconcile-what', to: 'resolve-reconciliation', on: 'runtime.completed' },
      { from: 'reconcile-what', to: 'resolve-reconciliation', on: 'runtime.failed' },
      { from: 'resolve-reconciliation', to: 'freeze-acceptance-baseline', on: 'domain.reconciled' },
      { from: 'resolve-reconciliation', to: 'reconcile-what', on: 'domain.repair-required' },
      { from: 'resolve-reconciliation', to: 'complete-inconsistent', on: 'domain.inconsistent' },
      { from: 'resolve-reconciliation', to: 'complete-clarification-required', on: 'domain.clarification-required' },
      { from: 'resolve-reconciliation', to: 'complete-failed', on: 'domain.failed' },

      { from: 'freeze-acceptance-baseline', to: 'define-architecture-contract', on: 'domain.frozen' },
      { from: 'freeze-acceptance-baseline', to: 'complete-inconsistent', on: 'domain.drift-detected' },
      { from: 'freeze-acceptance-baseline', to: 'complete-failed', on: 'domain.failed' },

      { from: 'define-architecture-contract', to: 'resolve-architecture-contract', on: 'runtime.completed' },
      { from: 'define-architecture-contract', to: 'resolve-architecture-contract', on: 'runtime.failed' },
      { from: 'resolve-architecture-contract', to: 'settle-formalization', on: 'domain.completed' },
      { from: 'resolve-architecture-contract', to: 'define-architecture-contract', on: 'domain.repair-required' },
      { from: 'resolve-architecture-contract', to: 'define-architecture-contract', on: 'domain.acceptance-blocked' },
      { from: 'resolve-architecture-contract', to: 'complete-infeasible', on: 'domain.infeasible' },
      { from: 'resolve-architecture-contract', to: 'complete-clarification-required', on: 'domain.clarification-required' },
      { from: 'resolve-architecture-contract', to: 'complete-inconsistent', on: 'domain.inconsistent' },
      { from: 'resolve-architecture-contract', to: 'complete-failed', on: 'domain.failed' },

      { from: 'settle-formalization', to: 'complete-formalized', on: 'domain.formalized' },
      { from: 'settle-formalization', to: 'complete-clarification-required', on: 'domain.clarification-required' },
      { from: 'settle-formalization', to: 'complete-inconsistent', on: 'domain.inconsistent' },
      { from: 'settle-formalization', to: 'complete-infeasible', on: 'domain.infeasible' },
      { from: 'settle-formalization', to: 'complete-failed', on: 'domain.failed' },
    ],
    recovery: [
      {
        id: 'repair-product-contract',
        verifyNodeId: 'resolve-product-contract',
        repairNodeId: 'define-product-contract',
        triggerEvents: ['domain.repair-required', 'domain.acceptance-blocked'],
        resolvedEvents: ['domain.completed'],
        maxAttempts: 2,
        onExhausted: 'pause',
      },
      {
        id: 'repair-use-case-contract',
        verifyNodeId: 'resolve-use-cases',
        repairNodeId: 'model-use-cases',
        triggerEvents: ['domain.repair-required', 'domain.acceptance-blocked'],
        resolvedEvents: ['domain.completed'],
        maxAttempts: 2,
        onExhausted: 'pause',
      },
      {
        id: 'repair-acceptance-contract',
        verifyNodeId: 'resolve-acceptance-contract',
        repairNodeId: 'define-acceptance-contract',
        triggerEvents: ['domain.repair-required', 'domain.acceptance-blocked'],
        resolvedEvents: ['domain.completed'],
        maxAttempts: 2,
        onExhausted: 'pause',
      },
      {
        id: 'repair-reconciliation',
        verifyNodeId: 'resolve-reconciliation',
        repairNodeId: 'reconcile-what',
        triggerEvents: ['domain.repair-required'],
        resolvedEvents: ['domain.reconciled'],
        maxAttempts: 2,
        onExhausted: 'escalate',
      },
      {
        id: 'repair-architecture-contract',
        verifyNodeId: 'resolve-architecture-contract',
        repairNodeId: 'define-architecture-contract',
        triggerEvents: ['domain.repair-required', 'domain.acceptance-blocked'],
        resolvedEvents: ['domain.completed'],
        maxAttempts: 2,
        onExhausted: 'escalate',
      },
    ],
    terminalNodeIds: [
      'complete-formalized',
      'complete-clarification-required',
      'complete-inconsistent',
      'complete-infeasible',
      'complete-failed',
    ],
  },
  artifacts: [
    { type: 'formalization-case', schema: { id: 'saga3.formalization-case.v1' }, authority: 'kernel', description: 'Input snapshot bound to the discovery certificate.' },
    { type: 'PRD', schema: { id: 'saga3.prd.v1' }, authority: 'worker', description: 'Product requirements document.' },
    { type: 'FR', schema: { id: 'saga3.functional-requirement.v1' }, authority: 'worker', description: 'Functional requirement.' },
    { type: 'NFR', schema: { id: 'saga3.non-functional-requirement.v1' }, authority: 'worker', description: 'Non-functional requirement.' },
    { type: 'RULE', schema: { id: 'saga3.business-rule.v1' }, authority: 'worker', description: 'Business rule with explicit enforcement trace.' },
    { type: 'UC', schema: { id: 'saga3.use-case.v1' }, authority: 'worker', description: 'Use case covering one or more FRs.' },
    { type: 'AC', schema: { id: 'saga3.acceptance-contract.v1' }, authority: 'worker', description: 'Acceptance criteria represented as contract data.' },
    { type: 'acceptance-baseline', schema: { id: 'saga3.acceptance-baseline-snapshot.v1' }, authority: 'kernel', description: 'Immutable accepted AC baseline.' },
    { type: 'SRS', schema: { id: 'saga3.srs.v1' }, authority: 'worker', description: 'Architecture and decomposition contract created after baseline freeze.' },
    { type: 'solution-contract-certificate', schema: { id: 'saga3.solution-contract-certificate.v1' }, authority: 'kernel', description: 'Authoritative result of the Formalization process.' },
  ],
  policies: [
    {
      id: 'formalization-what-reconciliation',
      version: '1.0.0',
      handler: 'formalization-what-reconciliation-policy',
      description: 'Requires complete WHAT-side traceability before baseline freeze.',
    },
    {
      id: 'formalization-settlement',
      version: '1.0.0',
      handler: 'formalization-settlement-policy',
      description: 'Validates the frozen acceptance and architecture graph before certification.',
    },
  ],
  invariants: [
    { id: 'formalization.what-before-how', description: 'PRD, FR, NFR, RULE, UC and AC are reconciled and frozen before SRS.', enforcement: 'runtime' },
    { id: 'formalization.trace-complete', description: 'Every accepted artifact has its required derived_from, covers or enforced_by links.', enforcement: 'policy' },
    { id: 'formalization.baseline-immutable', description: 'Accepted AC baseline cannot be edited in place.', enforcement: 'runtime' },
    { id: 'formalization.machine-fills-binding', description: 'Process, node, task, execution, artifact and schema identities are machine-filled.', enforcement: 'runtime' },
    { id: 'formalization.external-tracker', description: 'Every LM node maintains an external tracker and restart checkpoint.', enforcement: 'test' },
    { id: 'formalization.materialized-calls', description: 'Artifact, trace and completion MCP calls are materialized and checklist-verified.', enforcement: 'test' },
    { id: 'formalization.module-does-not-route', description: 'The module returns a local outcome and never starts Development directly.', enforcement: 'static' },
  ],
  executionProfiles: [
    {
      id: 'formalization-product',
      workIntentKind: 'formalization.product',
      workIntentSchema: { id: 'saga3.work-intent.formalization-product.v1' },
      taskKind: 'formalization.prd',
      executionSkill: 'saga-product',
      reviewSkill: 'saga-requirements-reviewer',
      protocolSkill: PROCESS_PROTOCOL_SKILL,
      semanticSkill: 'saga-product',
      artifactAcceptanceAuthority: 'kernel-gate',
      executionMode: 'artifact_change',
      allowedTools: COMMON_WRITE_TOOLS,
      trackerTemplate: TRACKER,
      workspaceTemplates: [ARTIFACT_CALL, TRACE_CALL, DONE_CALL],
      callTemplates: [ARTIFACT_CALL, TRACE_CALL, DONE_CALL],
      checklists: [CHECKLIST],
      outputSchema: { id: 'saga3.formalization-product-bundle.v1' },
      retryPolicy: { maxAttempts: 2, retryOn: ['schema-rejected', 'trace-gap'], backoff: 'none' },
      recoveryPolicy: { resumeFromCheckpoint: true, reuseWorkIntent: true, reuseAcceptedOutput: true, onExhausted: 'pause' },
    },
    {
      id: 'formalization-use-cases',
      workIntentKind: 'formalization.use-cases',
      workIntentSchema: { id: 'saga3.work-intent.formalization-use-cases.v1' },
      taskKind: 'formalization.uc',
      executionSkill: 'saga-analyst',
      reviewSkill: 'saga-requirements-reviewer',
      protocolSkill: PROCESS_PROTOCOL_SKILL,
      semanticSkill: 'saga-analyst',
      artifactAcceptanceAuthority: 'kernel-gate',
      executionMode: 'artifact_change',
      allowedTools: COMMON_WRITE_TOOLS,
      trackerTemplate: TRACKER,
      workspaceTemplates: [ARTIFACT_CALL, TRACE_CALL, DONE_CALL],
      callTemplates: [ARTIFACT_CALL, TRACE_CALL, DONE_CALL],
      checklists: [CHECKLIST],
      outputSchema: { id: 'saga3.formalization-use-case-bundle.v1' },
      retryPolicy: { maxAttempts: 2, retryOn: ['schema-rejected', 'trace-gap'], backoff: 'none' },
      recoveryPolicy: { resumeFromCheckpoint: true, reuseWorkIntent: true, reuseAcceptedOutput: true, onExhausted: 'pause' },
    },
    {
      id: 'formalization-acceptance',
      workIntentKind: 'formalization.acceptance',
      workIntentSchema: { id: 'saga3.work-intent.formalization-acceptance.v1' },
      taskKind: 'formalization.ac',
      executionSkill: 'saga-analyst',
      reviewSkill: 'saga-requirements-reviewer',
      protocolSkill: PROCESS_PROTOCOL_SKILL,
      semanticSkill: 'saga-analyst',
      artifactAcceptanceAuthority: 'kernel-gate',
      executionMode: 'artifact_change',
      allowedTools: COMMON_WRITE_TOOLS,
      trackerTemplate: TRACKER,
      workspaceTemplates: [ARTIFACT_CALL, TRACE_CALL, DONE_CALL],
      callTemplates: [ARTIFACT_CALL, TRACE_CALL, DONE_CALL],
      checklists: [CHECKLIST],
      outputSchema: { id: 'saga3.formalization-acceptance-bundle.v1' },
      retryPolicy: { maxAttempts: 2, retryOn: ['schema-rejected', 'trace-gap'], backoff: 'none' },
      recoveryPolicy: { resumeFromCheckpoint: true, reuseWorkIntent: true, reuseAcceptedOutput: true, onExhausted: 'pause' },
    },
    {
      id: 'formalization-reconciler',
      workIntentKind: 'formalization.reconcile',
      workIntentSchema: { id: 'saga3.work-intent.formalization-reconciliation.v1' },
      taskKind: 'formalization.reconciliation',
      executionSkill: 'saga-reconciler',
      reviewSkill: 'saga-requirements-reviewer',
      protocolSkill: PROCESS_PROTOCOL_SKILL,
      semanticSkill: 'saga-reconciler',
      artifactAcceptanceAuthority: 'kernel-gate',
      executionMode: 'artifact_change',
      allowedTools: COMMON_WRITE_TOOLS,
      trackerTemplate: TRACKER,
      workspaceTemplates: [TRACE_CALL, DONE_CALL],
      callTemplates: [TRACE_CALL, DONE_CALL],
      checklists: [CHECKLIST],
      outputSchema: { id: 'saga3.formalization-reconciliation-report.v1' },
      retryPolicy: { maxAttempts: 2, retryOn: ['trace-gap', 'baseline-race'], backoff: 'fixed' },
      recoveryPolicy: { resumeFromCheckpoint: true, reuseWorkIntent: true, reuseAcceptedOutput: true, onExhausted: 'escalate' },
    },
    {
      id: 'formalization-architect',
      workIntentKind: 'formalization.architecture',
      workIntentSchema: { id: 'saga3.work-intent.formalization-architecture.v1' },
      taskKind: 'formalization.srs',
      executionSkill: 'saga-architect',
      reviewSkill: 'saga-architecture-reviewer',
      protocolSkill: PROCESS_PROTOCOL_SKILL,
      semanticSkill: 'saga-architect',
      artifactAcceptanceAuthority: 'kernel-gate',
      executionMode: 'artifact_change',
      allowedTools: COMMON_WRITE_TOOLS,
      trackerTemplate: TRACKER,
      workspaceTemplates: [ARTIFACT_CALL, TRACE_CALL, DONE_CALL],
      callTemplates: [ARTIFACT_CALL, TRACE_CALL, DONE_CALL],
      checklists: [CHECKLIST],
      outputSchema: { id: 'saga3.formalization-architecture-bundle.v1' },
      retryPolicy: { maxAttempts: 2, retryOn: ['schema-rejected', 'trace-gap', 'invariant-gap'], backoff: 'none' },
      recoveryPolicy: { resumeFromCheckpoint: true, reuseWorkIntent: true, reuseAcceptedOutput: true, onExhausted: 'escalate' },
    },
  ],
};
