/**
 * W8-A1 — Formalization package manifest.
 *
 * Spec: `docs/refactor-management/09-contracts/WAVE8-FORMALIZATION-SPEC.md`.
 * Task: `docs/refactor-management/05-subagent-tasks/W08-a1.md`.
 *
 * This is the CENTRAL manifest for the Solution Formalization Process Module
 * package. Wave 8 is the first production module migration: Formalization runs
 * through PINNED PACKAGE RESOURCES with no fallback context, no global
 * skill/template lookup, and no direct infrastructure dependency
 * (WAVE8-FORMALIZATION-SPEC §2 exit gate).
 *
 * A1 OWNS this file exclusively. The other seven W8 lanes (A2..A8) submit
 * individual entries (node protocols, package-local resources, handler
 * adapters, contributions) to A1, which reconciles them into this single
 * manifest. Do not edit this file from another lane.
 *
 * What this manifest declares (plan §0.11.11):
 *   - `definition`               — the existing pure ProcessModuleDefinition
 *                                  (`formalization-process-module.ts`). Wraps
 *                                  it; does not duplicate it.
 *   - `resourceIndex`            — every skill, template, call-template and
 *                                  checklist the five formalization execution
 *                                  profiles reference. Pinned by `logicalId` +
 *                                  module-relative `path` so the runtime never
 *                                  does global resource lookup.
 *   - `handlerRefs`              — stable, content-addressed references to the
 *                                  seven kernel handlers declared in
 *                                  `formalization-installation.ts`.
 *   - `inputContractRef` /
 *     `outputContractRef`        — the FormalizationCase input contract and the
 *                                  SolutionContractCertificate output contract.
 *   - `runtimeCompatibilityRange`— the saga runtime API range this package
 *                                  requires.
 *
 * Purity (plan §3.5): the manifest is PURE DATA — no functions, no factories,
 * no class instances. Every field is canonically serializable so the Wave 2
 * content-addressed installer can persist + content-hash it verbatim. The
 * manifest is validated by `validateProcessModuleManifest` (W1-A2) at module
 * load; a structural regression throws synchronously and fails the build.
 *
 * Digest placeholder: every resource + handler digest uses the documented
 * `'pending@wave-2'` sentinel. The content-addressed package store (Wave 2)
 * replaces each placeholder with `sha256Hex` of the resource's real bytes at
 * install time. Until then the manifest is structurally complete and
 * serializable, but not yet content-addressed — exactly the Wave 8 contract.
 */

import type {
  HandlerRef,
  ProcessModuleManifest,
  ResourceIndexEntry,
} from '../../../domain/spi/module-manifest.js';
import {
  PENDING_DIGEST,
  validateProcessModuleManifest,
} from '../../../domain/spi/module-manifest.js';
import type { ContractRef } from '../../../domain/spi/contract-ref.js';
import { CONTRACT_REF_PENDING_DIGEST } from '../../../domain/spi/contract-ref.js';
import { formalizationProcessModule } from '../formalization-process-module.js';
import { FORMALIZATION_AGENT_ASSISTANCE } from './assistance.js';
import {
  FORMALIZATION_HANDLER_IDS,
  FORMALIZATION_MODULE_KEY,
} from '../../../../modules/formalization/application/formalization-installation.js';
import {
  FORMALIZATION_CASE_SCHEMA,
  SOLUTION_CONTRACT_CERTIFICATE_SCHEMA,
} from '../../../../modules/formalization/domain/formalization-schemas.js';

// ---------------------------------------------------------------------------
// Manifest format + runtime identity.
// ---------------------------------------------------------------------------

/**
 * Format version of THIS manifest envelope. `'1'` signals the envelope wraps a
 * migrated ProcessModuleDefinition that populates `resourceIndex` /
 * with empty arrays). Formalization uses the current manifest format.
 */
export const FORMALIZATION_MANIFEST_FORMAT_VERSION = '1';

/**
 * Runtime API compatibility range this package requires. Formalization was
 * migrated against the saga 3.x process-module SPI; the package is valid for
 * any 3.x runtime. The `<4.0.0` upper bound reserves room for the 4.x cutover.
 */
export const FORMALIZATION_RUNTIME_COMPATIBILITY_RANGE = '^3.0.0';

// ---------------------------------------------------------------------------
// Resource index.
//
// Every skill, instruction, template, call-template and checklist the five
// formalization execution profiles (product / use-cases / acceptance /
// reconciler / architect) reference is declared here. Paths are
// module-RELATIVE POSIX paths rooted at the repository root — the Wave 2
// installer resolves each under the package root and rejects absolute /
// traversal paths. `logicalId` is the stable, module-namespaced identifier the
// runtime pins against so it never falls back to global resource lookup
// (WAVE8-FORMALIZATION-SPEC §2.2).
// ---------------------------------------------------------------------------

/**
 * Repository-root-relative POSIX paths to the resources formalization pins.
 * (`tool-templates/formalization/`, `skills/saga-product|analyst|reconciler|
 * architect|requirements-reviewer|architecture-reviewer`) into the formalization
 * package resources directory. The resources physically live under
 * `src/process-modules/modules/formalization/package/resources/`; the manifest
 * pins them from the repo root so the workspace materializer +
 * content-addressed installer resolve them without module-private path
 * knowledge (mirrors the delivery package pattern). The shared
 * `saga-process-module-worker-protocol` skill stays a PLATFORM resource under
 * `skills/` (pinned by every process module); it is intentionally not
 * duplicated into each package.
 */
const FORMALIZATION_PACKAGE_RESOURCE_ROOT =
  'src/process-modules/modules/formalization/package/resources';
const RESOURCE_PATHS = {
  // Execution-profile skills (one per formalization LM node).
  productExecutionSkill: `${FORMALIZATION_PACKAGE_RESOURCE_ROOT}/skills/saga-product/SKILL.md`,
  analystExecutionSkill: `${FORMALIZATION_PACKAGE_RESOURCE_ROOT}/skills/saga-analyst/SKILL.md`,
  reconcilerExecutionSkill: `${FORMALIZATION_PACKAGE_RESOURCE_ROOT}/skills/saga-reconciler/SKILL.md`,
  architectExecutionSkill: `${FORMALIZATION_PACKAGE_RESOURCE_ROOT}/skills/saga-architect/SKILL.md`,
  // Reviewer skills (acceptance gates for each artifact tier).
  requirementsReviewerSkill: `${FORMALIZATION_PACKAGE_RESOURCE_ROOT}/skills/saga-requirements-reviewer/SKILL.md`,
  architectureReviewerSkill: `${FORMALIZATION_PACKAGE_RESOURCE_ROOT}/skills/saga-architecture-reviewer/SKILL.md`,
  // Shared protocol skill pinned by every formalization execution profile.
  // PLATFORM resource: stays at the repo-root skills/ dir (shared by all
  // process modules); not duplicated into the package.
  processProtocolSkill: 'skills/saga-process-module-worker-protocol/SKILL.md',
  // Workspace templates + call templates materialized by every LM node.
  artifactCreateCallTemplate: `${FORMALIZATION_PACKAGE_RESOURCE_ROOT}/artifact-create-call-template.json`,
  traceAddCallTemplate: `${FORMALIZATION_PACKAGE_RESOURCE_ROOT}/trace-add-call-template.json`,
  workerDoneCallTemplate: `${FORMALIZATION_PACKAGE_RESOURCE_ROOT}/worker-done-call-template.json`,
  reconciliationProductCallTemplate: `${FORMALIZATION_PACKAGE_RESOURCE_ROOT}/reconciliation-product-call-template.json`,
  // Reviewer-specific call template + checklist + tracker (role-contract parity).
  reviewVerdictCallTemplate: `${FORMALIZATION_PACKAGE_RESOURCE_ROOT}/review-verdict-call-template.json`,
  reviewerChecklist: `${FORMALIZATION_PACKAGE_RESOURCE_ROOT}/formalization-reviewer-checklist.md`,
  reviewerTracker: `${FORMALIZATION_PACKAGE_RESOURCE_ROOT}/formalization-reviewer-tracker.md`,
  // Per-node checklist + stage tracker pinned by every execution profile.
  nodeChecklist: `${FORMALIZATION_PACKAGE_RESOURCE_ROOT}/formalization-node-checklist.md`,
  stageTracker: `${FORMALIZATION_PACKAGE_RESOURCE_ROOT}/process-module-stage-tracker.md`,
} as const;

/**
 * The full resource index for the formalization package. Pinned by `logicalId`
 * (module-namespaced, unique within this manifest) so the runtime resolves
 * every resource through the package and never through global lookup.
 *
 * `digest` is the documented `'pending@wave-2'` placeholder: Wave 2's
 * content-addressed installer replaces it with `sha256Hex` of each resource's
 * real bytes at install time.
 */
export const FORMALIZATION_RESOURCE_INDEX: readonly ResourceIndexEntry[] = [
  // --- Execution skills (drive the LM nodes) -----------------------------
  {
    logicalId: 'formalization.skill.product-execution',
    path: RESOURCE_PATHS.productExecutionSkill,
    kind: 'skill',
    digest: PENDING_DIGEST,
  },
  {
    logicalId: 'formalization.skill.analyst-execution',
    path: RESOURCE_PATHS.analystExecutionSkill,
    kind: 'skill',
    digest: PENDING_DIGEST,
  },
  {
    logicalId: 'formalization.skill.reconciler-execution',
    path: RESOURCE_PATHS.reconcilerExecutionSkill,
    kind: 'skill',
    digest: PENDING_DIGEST,
  },
  {
    logicalId: 'formalization.skill.architect-execution',
    path: RESOURCE_PATHS.architectExecutionSkill,
    kind: 'skill',
    digest: PENDING_DIGEST,
  },
  // --- Reviewer skills (acceptance gates) --------------------------------
  {
    logicalId: 'formalization.skill.requirements-reviewer',
    path: RESOURCE_PATHS.requirementsReviewerSkill,
    kind: 'reviewer-skill',
    digest: PENDING_DIGEST,
  },
  {
    logicalId: 'formalization.skill.architecture-reviewer',
    path: RESOURCE_PATHS.architectureReviewerSkill,
    kind: 'reviewer-skill',
    digest: PENDING_DIGEST,
  },
  // --- Shared protocol skill ---------------------------------------------
  {
    logicalId: 'formalization.skill.process-protocol',
    path: RESOURCE_PATHS.processProtocolSkill,
    kind: 'instruction',
    digest: PENDING_DIGEST,
  },
  // --- Call templates (materialized MCP calls) ---------------------------
  {
    logicalId: 'formalization.template.artifact-create-call',
    path: RESOURCE_PATHS.artifactCreateCallTemplate,
    kind: 'mcp-call-template',
    digest: PENDING_DIGEST,
  },
  {
    logicalId: 'formalization.template.trace-add-call',
    path: RESOURCE_PATHS.traceAddCallTemplate,
    kind: 'mcp-call-template',
    digest: PENDING_DIGEST,
  },
  {
    logicalId: 'formalization.template.worker-done-call',
    path: RESOURCE_PATHS.workerDoneCallTemplate,
    kind: 'mcp-call-template',
    digest: PENDING_DIGEST,
  },
  {
    logicalId: 'formalization.template.reconciliation-product-call',
    path: RESOURCE_PATHS.reconciliationProductCallTemplate,
    kind: 'mcp-call-template',
    digest: PENDING_DIGEST,
  },
  // --- Reviewer-specific templates (role-contract parity) -----------------
  {
    logicalId: 'formalization.template.review-verdict-call',
    path: RESOURCE_PATHS.reviewVerdictCallTemplate,
    kind: 'mcp-call-template',
    digest: PENDING_DIGEST,
  },
  {
    logicalId: 'formalization.checklist.reviewer',
    path: RESOURCE_PATHS.reviewerChecklist,
    kind: 'checklist',
    digest: PENDING_DIGEST,
  },
  {
    logicalId: 'formalization.tracker.reviewer',
    path: RESOURCE_PATHS.reviewerTracker,
    kind: 'template',
    digest: PENDING_DIGEST,
  },
  // --- Checklists + stage tracker ----------------------------------------
  {
    logicalId: 'formalization.checklist.node',
    path: RESOURCE_PATHS.nodeChecklist,
    kind: 'checklist',
    digest: PENDING_DIGEST,
  },
  {
    logicalId: 'formalization.tracker.stage',
    path: RESOURCE_PATHS.stageTracker,
    kind: 'template',
    digest: PENDING_DIGEST,
  },
];

// ---------------------------------------------------------------------------
// Handler refs.
//
// Stable, content-addressed references to the seven kernel handlers the
// formalization flow wires up in `formalization-installation.ts`. Handlers are
// NOT shipped in the manifest — only stable references. The Wave 2+ adapter
// registry resolves each `logicalId` to the concrete `KernelHandler` by name.
// `digest` is the documented placeholder until the handler registry
// content-addresses handler implementations.
// ---------------------------------------------------------------------------

/** Shared placeholder handler version (matches the module version's minor). */
const HANDLER_VERSION = '1.0.0';

function formalizationHandlerRef(logicalId: string): HandlerRef {
  return {
    logicalId,
    version: HANDLER_VERSION,
    digest: PENDING_DIGEST,
  };
}

/**
 * The complete set of kernel handler references for the formalization package.
 * Each `logicalId` matches the `handler:` field declared on the corresponding
 * kernel node in `formalization-process-module.ts` and the key registered in
 * `FORMALIZATION_HANDLER_IDS` (`formalization-installation.ts`).
 */
export const FORMALIZATION_HANDLER_REFS: readonly HandlerRef[] = [
  formalizationHandlerRef(FORMALIZATION_HANDLER_IDS.resolveProduct),
  formalizationHandlerRef(FORMALIZATION_HANDLER_IDS.resolveUseCases),
  formalizationHandlerRef(FORMALIZATION_HANDLER_IDS.resolveAcceptance),
  formalizationHandlerRef(FORMALIZATION_HANDLER_IDS.resolveReconciliation),
  formalizationHandlerRef(FORMALIZATION_HANDLER_IDS.freezeBaseline),
  formalizationHandlerRef(FORMALIZATION_HANDLER_IDS.resolveArchitecture),
  formalizationHandlerRef(FORMALIZATION_HANDLER_IDS.settle),
];

// ---------------------------------------------------------------------------
// Contract refs.
//
// The input/output contracts of the formalization package. `schemaId` matches
// the `inputContract.id` / `outputContract.id` on the wrapped definition;
// `version`/`digest` are the documented Wave 8 placeholders until the
// ContractSchemaRegistry (W1-A5) ships concrete codecs behind each schema id.
// ---------------------------------------------------------------------------

/**
 * Build a ContractRef for a formalization schema id. Uses the documented
 * `CONTRACT_REF_PENDING_DIGEST` placeholder: Wave 2 replaces it with
 * `computeContractRefDigest(canonicalSchemaDocument)` once codecs land.
 */
function formalizationContractRef(schemaId: string): ContractRef {
  return {
    schemaId,
    version: '1.0.0',
    digest: CONTRACT_REF_PENDING_DIGEST,
  };
}

/** Input contract: one FormalizationCase bound to a discovery certificate. */
export const FORMALIZATION_INPUT_CONTRACT_REF: ContractRef = formalizationContractRef(
  FORMALIZATION_CASE_SCHEMA,
);

/** Output contract: the authoritative SolutionContractCertificate. */
export const FORMALIZATION_OUTPUT_CONTRACT_REF: ContractRef = formalizationContractRef(
  SOLUTION_CONTRACT_CERTIFICATE_SCHEMA,
);

// ---------------------------------------------------------------------------
// Central manifest.
// ---------------------------------------------------------------------------

/**
 * The central, validated ProcessModuleManifest for the Solution Formalization
 * package.
 *
 * This is the single object Wave 8 hands to the installer: it wraps the
 * existing pure {@link formalizationProcessModule} definition and declares the
 * pinned resources, handlers and contracts the module depends on. Other W8
 * lanes submit entries to A1, which reconciles them HERE — never edit this
 * constant from another lane.
 *
 * The manifest is validated at module load by
 * {@link validateProcessModuleManifest} (W1-A2), which enforces both canonical
 * serializability (plan §3.5 — no functions/Map/Set/class instances/undefined-
 * in-arrays/Symbols/non-finite numbers) and structural completeness (required
 * fields present, `logicalId`s unique, `resourceIndex` kinds known). A
 * regression throws synchronously and fails the build — the manifest is the
 * load-bearing seam between the pure definition and the content-addressed
 * package, so it must never load in an invalid state.
 */
export const formalizationPackageManifest: ProcessModuleManifest = (() => {
  const manifest: ProcessModuleManifest = {
    manifestFormatVersion: FORMALIZATION_MANIFEST_FORMAT_VERSION,
    definition: formalizationProcessModule,
    resourceIndex: FORMALIZATION_RESOURCE_INDEX,
    handlerRefs: FORMALIZATION_HANDLER_REFS,
    inputContractRef: FORMALIZATION_INPUT_CONTRACT_REF,
    outputContractRef: FORMALIZATION_OUTPUT_CONTRACT_REF,
    runtimeCompatibilityRange: FORMALIZATION_RUNTIME_COMPATIBILITY_RANGE,
    assistance: FORMALIZATION_AGENT_ASSISTANCE,
  };
  const validation = validateProcessModuleManifest(manifest);
  if (!validation.ok) {
    const rendered = validation.errors
      .map((e) => `  at ${e.path}: [${e.code}] ${e.message}`)
      .join('\n');
    throw new Error(
      `formalization package manifest failed validation:\n${rendered}`,
    );
  }
  return manifest;
})();

/**
 * Re-export the module key so consumers importing the manifest have the
 * canonical `name@version` identity on the same surface.
 */
export { FORMALIZATION_MODULE_KEY };
