import type { ProcessModuleDefinition } from '../../domain/process-module.js';
import { DISCOVERY_DIAGNOSIS_REPORT_SCHEMA } from '../../../saga3/domain/discovery-diagnosis-report.js';
import { DISCOVERY_NORMALIZATION_PROPOSAL_SCHEMA } from '../../../saga3/domain/discovery-normalization-proposal.js';
import { DISCOVERY_PROPOSAL_SCHEMA } from '../../../saga3/domain/discovery-proposal.js';
import { DISCOVERY_READINESS_ASSESSMENT_SCHEMA } from '../../../saga3/domain/discovery-readiness-assessment.js';
import {
  DISCOVERY_DIAGNOSIS_INTENT_KIND,
  DISCOVERY_INTENT_KIND,
  DISCOVERY_NORMALIZATION_INTENT_KIND,
  DISCOVERY_READINESS_INTENT_KIND,
  DISCOVERY_WORK_INTENT_SCHEMA,
} from '../../../saga3/domain/work-intent.js';

export const DISCOVERY_PROCESS_MODULE_REF = {
  name: 'product-discovery',
  version: '3.0.0',
} as const;

const DISCOVERY_TRACKER = 'tool-templates/discovery/stage-tracker.md';

export const discoveryProcessModule: ProcessModuleDefinition = {
  identity: {
    ...DISCOVERY_PROCESS_MODULE_REF,
    kind: 'discovery',
    displayName: 'Product Discovery',
    description: 'Turns an idea or problem into an authoritative discovery outcome certificate.',
  },
  inputContract: { id: 'saga3.discovery-case.v1' },
  outputContract: { id: 'saga3.discovery-outcome-certificate.v1' },
  outcomes: [
    { code: 'go', description: 'The subject is sufficiently grounded to continue.', terminal: true },
    { code: 'clarify', description: 'Material information is missing or contradictory.', terminal: true },
    { code: 'reject', description: 'The subject should not continue under the current evidence and policy.', terminal: true },
    { code: 'defer', description: 'The subject is valid but should be reconsidered later.', terminal: true },
    { code: 'inconclusive', description: 'Discovery completed without enough basis for another decision.', terminal: true },
    { code: 'failed', description: 'Discovery infrastructure could not produce an authoritative result.', terminal: true },
  ],
  flow: {
    id: 'saga3.discovery.standard',
    version: '1.0.0',
    entryNodeId: 'produce-proposal',
    nodes: [
      {
        id: 'produce-proposal',
        label: 'Produce Discovery Proposal',
        kind: 'lm',
        description: 'Investigate the bounded context and submit a typed DiscoveryProposal.',
        executionProfile: 'discovery-proposal-worker',
        outputSchema: { id: DISCOVERY_PROPOSAL_SCHEMA },
      },
      {
        id: 'normalize-deterministic',
        label: 'Normalize Deterministically',
        kind: 'kernel',
        description: 'Parse, remove supported fences and aliases, then validate without an LM call.',
        handler: 'discovery-normalization-kernel',
        inputSchema: { id: 'saga3.discovery-raw-submission.v1' },
        outputSchema: { id: DISCOVERY_PROPOSAL_SCHEMA },
      },
      {
        id: 'normalize-semantic',
        label: 'Normalize Semantic Ambiguity',
        kind: 'lm',
        description: 'Transform only ambiguous source fields without inventing evidence.',
        executionProfile: 'discovery-normalizer',
        outputSchema: { id: DISCOVERY_NORMALIZATION_PROPOSAL_SCHEMA },
      },
      {
        id: 'assess-readiness',
        label: 'Assess Readiness',
        kind: 'lm',
        description: 'Produce an advisory, source-bound readiness assessment for the canonical proposal.',
        executionProfile: 'discovery-readiness-advisor',
        outputSchema: { id: DISCOVERY_READINESS_ASSESSMENT_SCHEMA },
      },
      {
        id: 'settle',
        label: 'Settle Discovery',
        kind: 'kernel',
        description: 'Apply the versioned policy and issue the immutable authoritative certificate.',
        handler: 'discovery-settlement-policy',
        inputSchema: { id: 'saga3.discovery-settlement-input.v1' },
        outputSchema: { id: 'saga3.discovery-outcome-certificate.v1' },
      },
      {
        id: 'diagnose',
        label: 'Diagnose Outcome',
        kind: 'lm',
        description: 'Explain the issued certificate without changing its decision or authority.',
        executionProfile: 'discovery-diagnosis-advisor',
        outputSchema: { id: DISCOVERY_DIAGNOSIS_REPORT_SCHEMA },
      },
      ...[
        'go', 'clarify', 'reject', 'defer', 'inconclusive', 'failed',
      ].map(code => ({
        id: `complete-${code}`,
        label: `Complete: ${code}`,
        kind: 'kernel' as const,
        description: `Emit the local Discovery process outcome '${code}'.`,
        handler: 'process-outcome-emitter',
        emitsOutcome: code,
      })),
    ],
    transitions: [
      { from: 'produce-proposal', to: 'normalize-deterministic', on: 'submitted' },
      { from: 'produce-proposal', to: 'complete-failed', on: 'failed' },
      { from: 'normalize-deterministic', to: 'assess-readiness', on: 'accepted' },
      { from: 'normalize-deterministic', to: 'normalize-semantic', on: 'semantic-ambiguity' },
      { from: 'normalize-deterministic', to: 'complete-failed', on: 'invalid-json' },
      { from: 'normalize-semantic', to: 'assess-readiness', on: 'accepted' },
      { from: 'normalize-semantic', to: 'complete-failed', on: 'failed' },
      { from: 'assess-readiness', to: 'settle', on: 'completed' },
      { from: 'assess-readiness', to: 'settle', on: 'failed' },
      { from: 'assess-readiness', to: 'settle', on: 'paused' },
      { from: 'settle', to: 'diagnose', on: 'go' },
      { from: 'settle', to: 'diagnose', on: 'clarify' },
      { from: 'settle', to: 'diagnose', on: 'reject' },
      { from: 'settle', to: 'diagnose', on: 'defer' },
      { from: 'settle', to: 'diagnose', on: 'inconclusive' },
      { from: 'settle', to: 'complete-failed', on: 'failed' },
      { from: 'diagnose', to: 'complete-go', on: 'go' },
      { from: 'diagnose', to: 'complete-clarify', on: 'clarify' },
      { from: 'diagnose', to: 'complete-reject', on: 'reject' },
      { from: 'diagnose', to: 'complete-defer', on: 'defer' },
      { from: 'diagnose', to: 'complete-inconclusive', on: 'inconclusive' },
      { from: 'diagnose', to: 'complete-failed', on: 'failed-without-certificate' },
    ],
    terminalNodeIds: [
      'complete-go',
      'complete-clarify',
      'complete-reject',
      'complete-defer',
      'complete-inconclusive',
      'complete-failed',
    ],
  },
  artifacts: [
    { type: 'discovery-case', schema: { id: 'saga3.discovery-case.v1' }, authority: 'kernel', description: 'Immutable process input snapshot.' },
    { type: 'discovery-document', schema: { id: 'saga3.discovery-document.v1' }, authority: 'worker', description: 'Human-readable investigation record.' },
    { type: 'discovery-proposal', schema: { id: DISCOVERY_PROPOSAL_SCHEMA }, authority: 'worker', description: 'Typed worker proposal.' },
    { type: 'discovery-normalization-proposal', schema: { id: DISCOVERY_NORMALIZATION_PROPOSAL_SCHEMA }, authority: 'advisor', description: 'Source-bound semantic transformation proposal.' },
    { type: 'discovery-readiness-assessment', schema: { id: DISCOVERY_READINESS_ASSESSMENT_SCHEMA }, authority: 'advisor', description: 'Advisory readiness classification.' },
    { type: 'discovery-outcome-certificate', schema: { id: 'saga3.discovery-outcome-certificate.v1' }, authority: 'kernel', description: 'Immutable authoritative process result.' },
    { type: 'discovery-diagnosis-report', schema: { id: DISCOVERY_DIAGNOSIS_REPORT_SCHEMA }, authority: 'advisor', description: 'Advisory explanation of the certificate.' },
  ],
  policies: [
    {
      id: 'discovery-settlement',
      version: '1.0.0',
      handler: 'discovery-settlement-policy',
      description: 'The sole authority that converts proposal and readiness evidence into a decision.',
    },
  ],
  invariants: [
    { id: 'discovery.worker-proposes', description: 'LM workers propose but never settle or advance the lifecycle.', enforcement: 'runtime' },
    { id: 'discovery.kernel-authorizes', description: 'Only deterministic kernel policy issues the authoritative certificate.', enforcement: 'policy' },
    { id: 'discovery.machine-fills-binding', description: 'Known ids, hashes, schema versions and authority context are machine-filled.', enforcement: 'runtime' },
    { id: 'discovery.external-tracker', description: 'Every LM execution uses an external tracker as its program counter and recovery frame.', enforcement: 'test' },
    { id: 'discovery.materialized-calls', description: 'Typed MCP submissions are materialized and checklist-verified before invocation.', enforcement: 'test' },
    { id: 'discovery.diagnosis-advisory', description: 'Diagnosis may explain but never alter the certificate or route.', enforcement: 'runtime' },
  ],
  executionProfiles: [
    {
      id: 'discovery-proposal-worker',
      workIntentKind: DISCOVERY_INTENT_KIND,
      workIntentSchema: { id: DISCOVERY_WORK_INTENT_SCHEMA },
      taskKind: 'discovery.work',
      executionSkill: 'saga-discovery-worker',
      executionMode: 'tracker_only',
      allowedTools: [
        'task_get', 'repository_checkout_list', 'artifact_list', 'note_list',
        'proposal_submit', 'worker_done', 'Write', 'Read', 'Edit', 'Bash', 'Glob', 'Grep',
      ],
      trackerTemplate: DISCOVERY_TRACKER,
      workspaceTemplates: [
        'tool-templates/discovery/discovery-doc-template.md',
        'tool-templates/discovery/proposal-call-template.json',
      ],
      callTemplates: ['tool-templates/discovery/proposal-call-template.json'],
      checklists: ['tool-templates/discovery/proposal-checklist.md'],
      outputSchema: { id: DISCOVERY_PROPOSAL_SCHEMA },
      retryPolicy: { maxAttempts: 2, retryOn: ['schema-rejected', 'tool-error'], backoff: 'none' },
      recoveryPolicy: { resumeFromCheckpoint: true, reuseWorkIntent: true, reuseAcceptedOutput: true, onExhausted: 'fail' },
    },
    {
      id: 'discovery-normalizer',
      workIntentKind: DISCOVERY_NORMALIZATION_INTENT_KIND,
      workIntentSchema: { id: DISCOVERY_NORMALIZATION_PROPOSAL_SCHEMA },
      taskKind: 'discovery.normalize',
      executionSkill: 'saga-discovery-normalizer',
      executionMode: 'tracker_only',
      allowedTools: ['task_get', 'normalization_get', 'normalization_submit', 'worker_done', 'Read', 'Edit'],
      trackerTemplate: DISCOVERY_TRACKER,
      workspaceTemplates: ['tool-templates/discovery/normalization-call-template.json'],
      callTemplates: ['tool-templates/discovery/normalization-call-template.json'],
      checklists: ['tool-templates/discovery/normalization-checklist.md'],
      outputSchema: { id: DISCOVERY_NORMALIZATION_PROPOSAL_SCHEMA },
      retryPolicy: { maxAttempts: 2, retryOn: ['schema-rejected'], backoff: 'none' },
      recoveryPolicy: { resumeFromCheckpoint: true, reuseWorkIntent: true, reuseAcceptedOutput: true, onExhausted: 'fail' },
    },
    {
      id: 'discovery-readiness-advisor',
      workIntentKind: DISCOVERY_READINESS_INTENT_KIND,
      workIntentSchema: { id: DISCOVERY_READINESS_ASSESSMENT_SCHEMA },
      taskKind: 'discovery.assess',
      executionSkill: 'saga-discovery-readiness-advisor',
      executionMode: 'tracker_only',
      allowedTools: ['task_get', 'readiness_get', 'readiness_submit', 'worker_done', 'Read', 'Edit'],
      trackerTemplate: DISCOVERY_TRACKER,
      workspaceTemplates: ['tool-templates/discovery/readiness-call-template.json'],
      callTemplates: ['tool-templates/discovery/readiness-call-template.json'],
      checklists: ['tool-templates/discovery/readiness-checklist.md'],
      outputSchema: { id: DISCOVERY_READINESS_ASSESSMENT_SCHEMA },
      retryPolicy: { maxAttempts: 2, retryOn: ['schema-rejected'], backoff: 'none' },
      recoveryPolicy: { resumeFromCheckpoint: true, reuseWorkIntent: true, reuseAcceptedOutput: true, onExhausted: 'pause' },
    },
    {
      id: 'discovery-diagnosis-advisor',
      workIntentKind: DISCOVERY_DIAGNOSIS_INTENT_KIND,
      workIntentSchema: { id: DISCOVERY_DIAGNOSIS_REPORT_SCHEMA },
      taskKind: 'discovery.diagnose',
      executionSkill: 'saga-discovery-diagnosis-advisor',
      executionMode: 'tracker_only',
      allowedTools: ['task_get', 'diagnosis_get', 'diagnosis_submit', 'worker_done', 'Read', 'Edit'],
      trackerTemplate: DISCOVERY_TRACKER,
      workspaceTemplates: ['tool-templates/discovery/diagnosis-call-template.json'],
      callTemplates: ['tool-templates/discovery/diagnosis-call-template.json'],
      checklists: ['tool-templates/discovery/diagnosis-checklist.md'],
      outputSchema: { id: DISCOVERY_DIAGNOSIS_REPORT_SCHEMA },
      retryPolicy: { maxAttempts: 2, retryOn: ['schema-rejected'], backoff: 'none' },
      recoveryPolicy: { resumeFromCheckpoint: true, reuseWorkIntent: true, reuseAcceptedOutput: true, onExhausted: 'pause' },
    },
  ],
};
