// @ts-check
/**
 * W9-A3 — Development package central exports.
 *
 * Spec: `docs/refactor-management/09-contracts/WAVE9-PRODUCTION-MIGRATION-SPEC.md`.
 * Task: `docs/refactor-management/05-subagent-tasks/W09-a3.md`.
 *
 * Single import surface for the Development package. The Wave 11 composition
 * root and the W9-A8 conformance test import from here; downstream lanes
 * (W9-A4 contributions) sit alongside under
 * `modules/development/package/contributions/` and do not edit this file.
 *
 * Exports:
 *   - `developmentPackageManifest`       — the canonical ProcessModuleManifest.
 *   - `DEVELOPMENT_PACKAGE_RESOURCE_INDEX` — package-wide ResourceIndexEntry[].
 *   - `DEVELOPMENT_NODE_PROTOCOLS`         — NodeProtocolDefinition[] for the
 *                                            planning + verification nodes.
 *   - planning/verification node protocol, resources, handler refs, ids,
 *     schemas.
 *   - `DEVELOPMENT_PACKAGE_IDS`            — stable id constants join-keyed to
 *                                            the development Flow node ids.
 */

export { developmentPackageManifest } from './manifest.mjs';
export { default } from './manifest.mjs';

export {
  DEVELOPMENT_PACKAGE_RESOURCE_INDEX,
  DEVELOPMENT_PACKAGE_RESOURCE_LOGICAL_IDS,
  DEVELOPMENT_NODE_PROTOCOLS,
} from './resource-index.mjs';

export {
  PLANNING_NODE_ID,
  PLANNING_EXECUTION_PROFILE,
  PLANNING_OUTPUT_SCHEMA,
  PLANNING_RESOURCE_IDS,
  planningNodeProtocol,
  planningNodeResources,
  planningNodeHandlerRefs,
} from './nodes/planning/index.mjs';

export {
  VERIFICATION_NODE_ID,
  VERIFICATION_ADAPTER_ID,
  VERIFICATION_OUTPUT_SCHEMA,
  VERIFICATION_RESOURCE_IDS,
  verificationNodeProtocol,
  verificationNodeResources,
  verificationNodeHandlerRefs,
} from './nodes/verification/index.mjs';

/**
 * Stable id constants join-keyed to the development Flow node ids. The
 * composition root uses these to bind the runtime worker to each node without
 * switching on module-name strings (plan §3.6).
 */
export const DEVELOPMENT_PACKAGE_IDS = Object.freeze({
  planningNodeId: 'plan-task-graph',
  planningExecutionProfile: 'development-task-graph-planner',
  planningOutputSchema: 'saga3.development-task-graph-proposal.v1',
  verificationNodeId: 'verify-acceptance-workset',
  verificationAdapterId: 'development-verify-acceptance-workset',
  verificationOutputSchema: 'saga3.acceptance-verification-workset.v1',
});
