// @ts-check
/**
 * W9-A3 — Central Development package manifest.
 *
 * Spec: `docs/refactor-management/09-contracts/WAVE9-PRODUCTION-MIGRATION-SPEC.md`.
 * Task: `docs/refactor-management/05-subagent-tasks/W09-a3.md`.
 * Plan: §0.12.5 — this lane is the ONLY lane that edits the central Development
 * manifest. Other lanes (W9-A4 contributions) submit handler adapters behind
 * the handler refs declared here; they do not edit this file.
 *
 * This manifest is the canonical, persisted description of the Development
 * Process Module package. It deliberately contains NO executor, NO factories,
 * NO functions — only serializable data (plan §3.5). The Wave 2 installer
 * persists it verbatim; the Wave 3+ executors consume it read-only.
 *
 * It wraps the existing pure `developmentProcessModule` definition (reused, not
 * redefined) and surfaces the package-wide `resourceIndex` + `handlerRefs` +
 * rich input/output `ContractRef`s that Wave 9 pins. The `resourceIndex` is
 * stitched from the planning + verification node subtrees via
 * `./resource-index.mjs`; the handler refs come from each node's declared
 * downstream handler.
 *
 * The TypeScript ProcessModuleManifest type lives in
 * `src/process-modules/domain/spi/module-manifest.ts`. This `.mjs` mirror is the
 * package-local pure-data instance; the companion test imports the validator
 * from `dist/` to assert it passes `validateProcessModuleManifest`.
 *
 * Anti-scope: this lane does NOT register handler implementations (W9-A4 owns
 * `modules/development/package/contributions/`), does NOT touch Runtime /
 * runner / gateway / catalog / another module (plan §0.12.11), and performs no
 * composition-root cutover (Wave 11).
 */

// Value imports resolve against the COMPILED dist/ tree (tsc emits
// dist/process-modules/...). The package source lives in TypeScript under
// src/, so a src/ import would not resolve under Node at runtime. The Wave 8
// Formalization pilot established this pattern: package-local .mjs files carry
// pure data + JSDoc type-only imports, and value imports of the module
// definition come from dist/ (the test surface runs `tsc` first). The build
// step (`npm run build`) keeps dist/ in sync before any consumer runs.
import { developmentProcessModule } from '../../../dist/process-modules/modules/development/development-process-module.js';
import { DEVELOPMENT_CASE_SCHEMA, VERIFIED_INTEGRATION_BUNDLE_SCHEMA } from '../../../dist/process-modules/modules/development/development-schemas.js';
import {
  DEVELOPMENT_PACKAGE_RESOURCE_INDEX,
  DEVELOPMENT_PACKAGE_RESOURCE_LOGICAL_IDS,
  DEVELOPMENT_NODE_PROTOCOLS,
} from './resource-index.mjs';
import { planningNodeHandlerRefs } from './nodes/planning/node-protocol.mjs';
import { verificationNodeHandlerRefs } from './nodes/verification/node-protocol.mjs';

/**
 * @typedef {import('../../../src/process-modules/domain/spi/module-manifest.ts').ProcessModuleManifest} ProcessModuleManifest
 * @typedef {import('../../../src/process-modules/domain/spi/module-manifest.ts').HandlerRef} HandlerRef
 * @typedef {import('../../../src/process-modules/domain/spi/contract-ref.ts').ContractRef} ContractRef
 */

/** Placeholder digest Wave 9 callers use until the Wave 2 installer computes the real hash. */
const PENDING = 'pending@wave-2';

/**
 * Rich input contract reference for the Development module
 * (`saga3.development-case.v1`). `digest` is provisional until Wave 2.
 *
 * @type {ContractRef}
 */
const DEVELOPMENT_INPUT_CONTRACT_REF = Object.freeze({
  schemaId: DEVELOPMENT_CASE_SCHEMA,
  version: '1.0.0',
  digest: PENDING,
});

/**
 * Rich output contract reference for the Development module
 * (`saga3.verified-integration-bundle.v1`). `digest` is provisional until
 * Wave 2.
 *
 * @type {ContractRef}
 */
const DEVELOPMENT_OUTPUT_CONTRACT_REF = Object.freeze({
  schemaId: VERIFIED_INTEGRATION_BUNDLE_SCHEMA,
  version: '1.0.0',
  digest: PENDING,
});

/**
 * Stable handler refs the Development module declares. Concatenated from each
 * node subtree's downstream kernel handler. W9-A4 binds the real handler
 * adapters behind these logical ids. `logicalId` is unique within the package.
 *
 * @type {readonly HandlerRef[]}
 */
const DEVELOPMENT_HANDLER_REFS = Object.freeze([
  ...planningNodeHandlerRefs,
  ...verificationNodeHandlerRefs,
]);

/**
 * The canonical Development package manifest. Pure, serializable data only.
 *
 * @type {ProcessModuleManifest}
 */
export const developmentPackageManifest = Object.freeze({
  manifestFormatVersion: '0.1.0',
  definition: developmentProcessModule,
  resourceIndex: DEVELOPMENT_PACKAGE_RESOURCE_INDEX,
  handlerRefs: DEVELOPMENT_HANDLER_REFS,
  inputContractRef: DEVELOPMENT_INPUT_CONTRACT_REF,
  outputContractRef: DEVELOPMENT_OUTPUT_CONTRACT_REF,
  // Development targets the same Runtime API as the Formalization pilot (Wave 8).
  runtimeCompatibilityRange: '^3.0.0',
});

/**
 * Convenience re-exports of the stitched package surfaces, so consumers (and
 * the W9-A8 conformance test) can import the full manifest surface from one
 * module via the central `index.mjs`.
 */
export {
  DEVELOPMENT_PACKAGE_RESOURCE_INDEX,
  DEVELOPMENT_PACKAGE_RESOURCE_LOGICAL_IDS,
  DEVELOPMENT_NODE_PROTOCOLS,
} from './resource-index.mjs';

export {
  PLANNING_NODE_ID,
  PLANNING_EXECUTION_PROFILE,
  PLANNING_OUTPUT_SCHEMA,
  planningNodeProtocol,
  planningNodeResources,
  planningNodeHandlerRefs,
} from './nodes/planning/node-protocol.mjs';

export {
  VERIFICATION_NODE_ID,
  VERIFICATION_ADAPTER_ID,
  VERIFICATION_OUTPUT_SCHEMA,
  verificationNodeProtocol,
  verificationNodeResources,
  verificationNodeHandlerRefs,
} from './nodes/verification/node-protocol.mjs';

export default developmentPackageManifest;
